# -*- coding: utf-8 -*-
"""LLM_Prompt_Eng vs Context_Eng .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_DwwYqvsw9aMmG4ONzBGV35-PifVIhEC

# LLM Systems Notebook: Prompt Engineering → Context Engineering → Production



**Core insight:** Prompt engineering is *what you say*. Context engineering is *everything the model knows*. Production LLM systems require both.

# Section 0 — Setup & Configuration
"""

# Install all required packages with pinned minimum versions.
# Pinning prevents silent breakage — a common production mistake.

!pip install -q \
    transformers>=4.40.0 \
    torch>=2.1.0 \
    accelerate>=0.27.0 \
    sentence-transformers>=2.5.0 \
    datasets>=2.18.0 \
    pydantic>=2.0.0 \
    langchain>=0.1.17 \
    openai>=1.13.0 \
    faiss-cpu>=1.7.4 \
    duckduckgo-search>=5.2.0

print('All packages installed')

# import libraires

import json, re, time, warnings
from dataclasses import dataclass
from typing import Optional

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, GenerationConfig, pipeline

warnings.filterwarnings('ignore')

# Know your hardware before loading a 4B model
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'Device: {device}')
if device == 'cuda':
    print(f'GPU: {torch.cuda.get_device_name(0)}')
    vram = torch.cuda.get_device_properties(0).total_memory / 1e9
    print(f'VRAM: {vram:.1f} GB')
else:
    print('Warning: No GPU — inference will be slow on CPU')

# --- Configuration dataclass ---

# Single source of truth for all model and generation parameters.
# Change model_id here and the entire notebook adapts automatically.
# Trivial to log to MLflow or Weights & Biases later.

@dataclass
class LLMConfig:
    model_id: str = 'microsoft/Phi-3-mini-4k-instruct'
    torch_dtype: str = 'auto'       # 'auto' picks bf16/fp16 intelligently
    device_map: str = 'cuda'        # use 'cpu' if no GPU; 'auto' for multi-GPU
    trust_remote_code: bool = False  # only True for models that require it
    max_new_tokens: int = 500
    do_sample: bool = False          # False = deterministic greedy decoding
    temperature: float = 1.0
    top_p: float = 1.0
    top_k: int = 50

cfg = LLMConfig()
print(f'Model : {cfg.model_id}')
print(f'Device: {cfg.device_map} | Dtype: {cfg.torch_dtype}')

"""---
# Section 1 — Model Loading & Chat Templates


Every instruct/chat-tuned model is trained with a specific conversation format — special tokens that delimit system instructions, user messages, and assistant turns. If you skip the template and feed raw text, the model gets confused because the input does not match its training distribution.

For Phi-3 the format is:
```
<|user|>\nHello<|end|>\n<|assistant|>\n
```

`tokenizer.apply_chat_template()` handles this automatically and is the **correct** way.

"""

# Load tokenizer and model separately — more explicit control than
# letting pipeline handle everything. Matters when you want to:
#   - inspect token IDs
#   - run batched inference
#   - add custom stopping criteria

print(f'Loading tokenizer...')
tokenizer = AutoTokenizer.from_pretrained(cfg.model_id)

print(f'Loading model (may take a minute on first run)...')
model = AutoModelForCausalLM.from_pretrained(
    cfg.model_id,
    device_map=cfg.device_map,
    torch_dtype=cfg.torch_dtype,
    trust_remote_code=cfg.trust_remote_code,
)

# return_full_text=False strips the echoed input so we only see the model reply

pipe = pipeline('text-generation', model=model, tokenizer=tokenizer, return_full_text=False)

params = model.num_parameters() / 1e9
print(f'Model loaded | Parameters: {params:.2f}B')

# --- Reusable Inference Wrapper ---

# we use One clean wrapper that:
#   - uses GenerationConfig (modern, validated, serializable)
#   - returns just the text string
#   - optionally tracks latency

def generate(
    messages: list[dict],
    *,
    max_new_tokens: int = 500,
    do_sample: bool = False,
    temperature: float = 1.0,
    top_p: float = 1.0,
    top_k: int = 50,
    repetition_penalty: float = 1.0,
    show_latency: bool = False,
) -> str:
    """Run inference and return the assistant reply as a string."""
    gen_cfg = GenerationConfig(
        max_new_tokens=max_new_tokens,
        do_sample=do_sample,
        temperature=temperature if do_sample else 1.0,
        top_p=top_p if do_sample else 1.0,
        top_k=top_k if do_sample else 50,
        repetition_penalty=repetition_penalty,
    )
    t0 = time.time()
    outputs = pipe(messages, generation_config=gen_cfg)
    elapsed = time.time() - t0
    reply = outputs[0]['generated_text']
    if show_latency:
        n_tok = len(tokenizer.encode(reply))
        print(f'  {elapsed:.2f}s | {n_tok} tokens | {n_tok/elapsed:.1f} tok/s')
    return reply


# Quick smoke test
reply = generate([{'role': 'user', 'content': 'Say hello in one sentence.'}],
                 max_new_tokens=40, show_latency=True)
print(reply)

# --- Chat Template Inspection ---


# Understanding what the model actually receives is critical debugging skill.
# apply_chat_template(tokenize=False) shows the raw formatted string.
# apply_chat_template(tokenize=True) shows the token ID list.

sample_messages = [{'role': 'user', 'content': 'Create a funny joke about chickens.'}]

print('=== Formatted string (what the model reads) ===')
formatted = tokenizer.apply_chat_template(
    sample_messages, tokenize=False, add_generation_prompt=True
)
print(repr(formatted))

print('\n=== Token IDs (what flows into the model) ===')
encoding = tokenizer.apply_chat_template(
    sample_messages, tokenize=True, add_generation_prompt=True
)

# ─  Extract input_ids from the Encoding object ────────
token_ids = encoding.input_ids  # ← This is the actual list[int]

print(f'Token count: {len(token_ids)}')
print(f'First 15 IDs: {token_ids[:15]}')
print(f'Decoded     : {tokenizer.decode(token_ids[:15])}')

# ──  See all fields in the Encoding ──────────────────
print(f'\n === Full Encoding object (dict-like) ===')
print(f'Keys: {encoding.keys()}')
for key in encoding.keys():
    print(f'  {key}: {getattr(encoding, key)[:5] if hasattr(getattr(encoding, key), "__getitem__") else getattr(encoding, key)}')

"""---
# Section 2 — Decoding Strategies

## The most important inference-time knob

After the model computes a probability distribution over the next token, it must **choose** which token to emit. That choice algorithm is the decoding strategy.

| Strategy | Mechanism | Output | Best For |
|----------|-----------|--------|---------|
| **Greedy** | Always pick highest-prob token | Deterministic | Extraction, classification, QA |
| **Temperature** | Scale logits by 1/T before softmax | Higher T = more random | Creative tasks |
| **Top-k** | Sample from k highest-prob tokens | Bounded diversity | Variety without gibberish |
| **Top-p (nucleus)** | Sample from smallest set summing to p | Adaptive diversity | Most chat models |
| **Combined** | temp + top_p + top_k | Best of all | Production default |

**Math:** `p_i = softmax(z_i / T)`. T→0 = greedy. T→∞ = uniform random.


"""

# --- Experiment Runner ---


# Define experiments as data, not as repeated code.
# This is production thinking: one loop, many configs.

def run_decoding_experiment(messages, experiments, max_new_tokens=120):
    """Run a list of decoding experiments and print formatted comparison."""
    print('=' * 65)
    for exp in experiments:
        label = exp.pop('label')
        print(f'\n[{label}]')
        print(generate(messages, max_new_tokens=max_new_tokens, **exp).strip())
        print('-' * 65)
        exp['label'] = label


joke_messages = [{'role': 'user', 'content': 'Create a funny joke about chickens.'}]

# Greedy decoding: do_sample=False — highest-prob token every step.
# 100% deterministic: run this cell twice, get identical output.
# This is the right choice for tasks requiring consistency.

print('GREEDY (deterministic):')
print(generate(joke_messages, do_sample=False, max_new_tokens=120))

# Temperature comparison

# Low T = confident/focused output.
# High T = surprising/risky output.

temperature_experiments = [
    {'label': 'temp=0.1  (very focused)',  'do_sample': True, 'temperature': 0.1},
    {'label': 'temp=0.7  (balanced)',      'do_sample': True, 'temperature': 0.7},
    {'label': 'temp=1.0  (neutral)',       'do_sample': True, 'temperature': 1.0},
    {'label': 'temp=1.5  (very creative)', 'do_sample': True, 'temperature': 1.5},
]
print('TEMPERATURE COMPARISON')
run_decoding_experiment(joke_messages, temperature_experiments)

# Top-p: adaptive nucleus — pool adapts to the model's confidence.
# p=0.9 is the most common production default (OpenAI, Anthropic, etc.)

top_p_experiments = [
    {'label': 'top_p=0.1 (narrow nucleus)',   'do_sample': True, 'top_p': 0.1},
    {'label': 'top_p=0.5 (moderate)',         'do_sample': True, 'top_p': 0.5},
    {'label': 'top_p=0.9 (production default)','do_sample': True, 'top_p': 0.9},
    {'label': 'top_p=1.0 (full distribution)', 'do_sample': True, 'top_p': 1.0},
]
print('TOP-P COMPARISON')
run_decoding_experiment(joke_messages, top_p_experiments)

# Top-k: fixed number of candidates (less adaptive than top-p).
# top_k=1 is equivalent to greedy.
# top_k=50 is a common default.

top_k_experiments = [
    {'label': 'top_k=1  (greedy equivalent)', 'do_sample': True, 'top_k': 1},
    {'label': 'top_k=8  (narrow)',            'do_sample': True, 'top_k': 8},
    {'label': 'top_k=50 (default)',           'do_sample': True, 'top_k': 50},
    {'label': 'top_k=200 (wide)',             'do_sample': True, 'top_k': 200},
]
print('TOP-K COMPARISON')
run_decoding_experiment(joke_messages, top_k_experiments)

# combine temperature + top_p (the standard approach).

# Most APIs (GPT-4, Claude, Gemini) use this combination internally.

production_presets = [
    {'label': 'Factual / extraction',       'do_sample': False},
    {'label': 'Balanced chat (t=0.7 p=0.9)','do_sample': True, 'temperature': 0.7, 'top_p': 0.9},
    {'label': 'Creative (t=1.1 p=0.95)',    'do_sample': True, 'temperature': 1.1, 'top_p': 0.95},
]
print('PRODUCTION DECODING PRESETS')
run_decoding_experiment(joke_messages, production_presets)

"""---
# Section 3 — Prompt Engineering

**Prompt engineering** is the practice of crafting text instructions to elicit the best possible response without changing model weights.

> Prompt engineering controls *what you say*. Context engineering controls *everything the model knows*. Production systems require both.

## Techniques overview

| Technique | Definition | Best For |
|-----------|-----------|----------|
| **Zero-shot** | No examples | General tasks, well-known formats |
| **Few-shot** | 2-8 examples in context | Classification, format alignment |
| **Structured** | Named components (PICT-AT) | Professional/enterprise tasks |
| **Chain** | Output of step N feeds step N+1 | Complex multi-step tasks |

"""

# --- Zero-shot vs One-shot for novel word definition ---
# The model has never seen 'screeg'. One-shot example teaches format from context.

zero_shot = [{'role': 'user',
               'content': "To 'screeg' something is to swing a sword at it. An example sentence:"}]

one_shot = [
    # Example teaches the expected output format
    {'role': 'user',      'content': "A 'Gigamuru' is a type of Japanese musical instrument. An example sentence:"},
    {'role': 'assistant', 'content': 'I have a Gigamuru that my uncle gave me as a gift.'},
    {'role': 'user',      'content': "To 'screeg' something is to swing a sword at it. An example sentence:"},
]

print('ZERO-SHOT:')
print(generate(zero_shot, max_new_tokens=60))
print('\nONE-SHOT:')
print(generate(one_shot, max_new_tokens=60))
print('\nOne-shot typically matches the format of the example more closely.')

# --- Few-shot sentiment classification ---

# Model infers the task and output format from examples alone — no task description.
# This is in-context learning: no weight updates required.

# --- Few-shot sentiment classification (Fixed) ---

few_shot_examples = [
    {'role': 'user',      'content': 'I think the food was alright.'},
    {'role': 'assistant', 'content': 'Neutral'},

    {'role': 'user',      'content': 'The movie was absolutely terrible, a waste of time.'},
    {'role': 'assistant', 'content': 'Negative'},

    {'role': 'user',      'content': 'This is the best coffee I have ever had!'},
    {'role': 'assistant', 'content': 'Positive'},

    # Optional: Add a mixed example for better performance
    {'role': 'user',      'content': 'The room was clean but the WiFi was terrible.'},
    {'role': 'assistant', 'content': 'Mixed'},
]

# Test input
test_input = "The service was okay but the dessert was amazing."

# Build full prompt
prompt = few_shot_examples + [{'role': 'user', 'content': test_input}]

pred = generate(prompt, max_new_tokens=30).strip()

print(f"Input: {test_input}")
print(f"Prediction: {pred}")

# --- Structured prompt builder (PICT-AT framework) ---

# Modular: remove any component to run ablation experiments.
# This is how we systematically improve prompts rather than guessing.

def build_structured_prompt(text, persona='', instruction='', context='',
                             data_format='', audience='', tone='') -> str:
    """Assemble a structured prompt from named components (PICT-AT)."""
    parts = [c for c in [persona, instruction, context, data_format, audience, tone, text] if c.strip()]
    return '\n'.join(parts)


transformer_text = """\
The Transformer was introduced in 'Attention is All You Need' (Vaswani et al., 2017).
It uses self-attention to process all positions in parallel, enabling faster training
than sequential RNN-based models. The encoder-decoder architecture with multi-head attention
and positional encodings became the foundation for BERT, GPT, and virtually all modern LLMs."""

full_prompt = build_structured_prompt(
    text=f'Text to summarize:\n{transformer_text}',
    persona='You are an ML research expert who excels at clear, concise explanations.',
    instruction='Summarize the key findings of the provided text.',
    context='Extract the most crucial points so researchers can quickly grasp the contribution.',
    data_format='Use bullet points for the method, then one concise paragraph for results.',
    audience='Busy ML researchers.',
    tone='Professional and clear.',
)

print(f'Prompt tokens: {len(tokenizer.encode(full_prompt))}')
print('\n--- Generated Summary ---')
print(generate([{'role': 'user', 'content': full_prompt}], max_new_tokens=300))

# --- Prompt ablation study ---

# Remove components one at a time to measure their impact.
# This is the evidence-based way to improve prompts.

ablation_configs = [
    {'label': 'Full (persona+format+audience+tone)',
     'persona': 'You are an ML expert.', 'data_format': 'Bullet points then one paragraph.',
     'audience': 'ML researchers.', 'tone': 'Professional.'},
    {'label': 'No persona',
     'data_format': 'Bullet points then one paragraph.',
     'audience': 'ML researchers.', 'tone': 'Professional.'},
    {'label': 'Minimal (instruction only)',},
]

short_text = transformer_text[:300]
print('=== PROMPT ABLATION STUDY ===')
for cfg_dict in ablation_configs:
    label = cfg_dict.pop('label')
    prompt = build_structured_prompt(text=f'Text:\n{short_text}',
                                     instruction='Summarize the following text.', **cfg_dict)
    reply = generate([{'role': 'user', 'content': prompt}], max_new_tokens=120)
    print(f'\n[{label}]\n{reply.strip()}')
    print('-' * 60)
    cfg_dict['label'] = label

# --- Chain prompting: Name -> Slogan -> Sales Pitch -> Social Post ---

# The output of each step feeds into the next.
# In production: add validation and error handling between steps.
# Chain prompting is the precursor to agentic workflows.

def chain_prompt_pipeline(topic: str) -> dict:
    """Three-step prompt chain demonstrating output chaining."""

    step1 = generate(
        [{'role': 'user', 'content': f'Create a name and one-line slogan for: {topic}. Format: Name: X\nSlogan: Y'}],
        max_new_tokens=60, do_sample=True, temperature=0.8
    )

    step2 = generate(
        [{'role': 'user', 'content': f'Write a 2-sentence sales pitch for:\n{step1}'}],
        max_new_tokens=80, do_sample=True, temperature=0.7
    )

    step3 = generate(
        [{'role': 'user', 'content': f'Write a Twitter/X post (max 280 chars) for:\n{step2}'}],
        max_new_tokens=60, do_sample=True, temperature=0.9
    )

    return {'name_and_slogan': step1.strip(), 'sales_pitch': step2.strip(), 'social_post': step3.strip()}


result = chain_prompt_pipeline('Generative AI Training Center')
for step, output in result.items():
    print(f'\n=== {step.upper().replace("_", " ")} ===')
    print(output)

"""---
# Section 4 — Reasoning Strategies

Standard prompts ask the model to jump straight to the answer. For complex multi-step problems, this fails — the model lacks 'thinking space'. Reasoning prompting gives it room to work through problems sequentially.

**Key paper:** *Chain-of-Thought Prompting Elicits Reasoning in Large Language Models* (Wei et al., 2022)

| Technique | Mechanism | Best For |
|-----------|-----------|----------|
| **Standard** | Direct question → answer | Simple facts |
| **Few-shot CoT** | Show reasoning steps in examples | Math, logic, multi-step |
| **Zero-shot CoT** | Append 'Let's think step by step' | Quick boost without examples |
| **Tree-of-Thought** | Explore multiple reasoning branches | Complex open-ended problems |

"""

# --- Chain-of-Thought: Standard vs CoT ---

# The key difference is the ASSISTANT's example response:
# Standard: just gives the answer
# CoT: shows the reasoning that leads to the answer
# The model learns from the example that it should reason before answering.

CAFETERIA_Q = 'The cafeteria had 23 apples. They used 20 for lunch and bought 6 more. How many apples now?'

standard_prompt = [
    {'role': 'user',      'content': 'Roger has 5 tennis balls. He buys 2 cans of 3 balls each. Total?'},
    {'role': 'assistant', 'content': '11'},  # No reasoning shown
    {'role': 'user',      'content': CAFETERIA_Q},
]

cot_prompt = [
    {'role': 'user',      'content': 'Roger has 5 tennis balls. He buys 2 cans of 3 balls each. Total?'},
    {'role': 'assistant', 'content': 'Roger started with 5. 2 cans x 3 = 6 new balls. 5 + 6 = 11. The answer is 11.'},
    {'role': 'user',      'content': CAFETERIA_Q},
]

zeroshot_cot_prompt = [
    # No example needed — the magic phrase activates reasoning
    {'role': 'user', 'content': f'{CAFETERIA_Q} Let\'s think step by step.'}
]

for label, msgs in [('STANDARD', standard_prompt), ('CHAIN-OF-THOUGHT', cot_prompt), ('ZERO-SHOT CoT', zeroshot_cot_prompt)]:
    print(f'\n=== {label} ===')
    print(generate(msgs, max_new_tokens=180, do_sample=False).strip())

# --- Tree-of-Thought: Multiple Experts Simulation ---


# Instead of one linear reasoning chain, we prompt for multiple perspectives.
# This is a prompt-only approximation of ToT (Yao et al., 2023).
# True ToT requires an orchestration layer for branching and evaluation.

tot_prompt = """\
Imagine three expert mathematicians solving this problem together.
Each writes ONE step of thinking, then shares with the group.
They continue step by step. If any expert realizes they are wrong, they acknowledge it.
All three then agree on the final answer.

Problem: The cafeteria had 23 apples. They used 20 for lunch and bought 6 more.
How many apples do they have now?

Begin:"""

print('TREE-OF-THOUGHT (multiple experts simulation):')
print(generate([{'role': 'user', 'content': tot_prompt}],
               max_new_tokens=400, do_sample=True, temperature=0.7))

"""---
# Section 5 — Structured Output Generation

In real applications, LLM outputs flow into databases, APIs, and UIs — not just human readers. An LLM that outputs prose when we needed JSON breaks ours pipeline.

## Techniques (easiest to most robust)

| Technique | Robustness | When to Use |
|-----------|------------|------------|
| Prompt-only | Fragile | Prototyping |
| Schema in prompt | Moderate | Low-scale production |
| Few-shot JSON examples | Good | Medium-scale |
| Pydantic validation + retry | Very good | Production |
| Grammar-constrained decoding | Guaranteed | High-volume production |



"""

# --- Schema-in-Prompt (minimum viable structured output) ---


# Providing the exact schema significantly improves reliability.
# The model knows exactly what keys to use and what types to provide.

RPG_SCHEMA = {
    'name': 'string',
    'class': 'warrior | mage | rogue | paladin',
    'level': 'integer 1-20',
    'hp': 'integer > 0',
    'weapon': 'string',
    'armor': 'string',
    'backstory': 'string (max 2 sentences)',
}

schema_prompt = (
    'Create a character profile for a fantasy RPG game.\n'
    'Respond with ONLY valid JSON matching exactly this schema:\n'
    f'{json.dumps(RPG_SCHEMA, indent=2)}\n'
    'Rules: no markdown code blocks, no explanations, all fields present, valid parseable JSON.'
)

output = generate([{'role': 'user', 'content': schema_prompt}], max_new_tokens=250, do_sample=False)
print('RAW OUTPUT:')
print(output)

try:
    data = json.loads(output.strip())
    missing = [k for k in RPG_SCHEMA if k not in data]
    print(f'\nParsed OK | Missing fields: {missing or "none"}')
except json.JSONDecodeError as e:
    print(f'\nParse failed: {e}')

"""### --- Pydantic Validation + Retry Loop  ---"""

# --- Pydantic Validation + Retry Loop (production pattern) ---


# 1. Define schema as a Pydantic model
# 2. Generate output
# 3. Try to parse and validate
# 4. If validation fails, send the error back to the model for self-correction
# This self-healing loop handles ~95% of edge cases automatically.

from pydantic import BaseModel, Field, ValidationError
from typing import Literal

class RPGCharacter(BaseModel):
    name: str
    character_class: Literal['warrior', 'mage', 'rogue', 'paladin']
    level: int = Field(..., ge=1, le=20)
    hp: int = Field(..., gt=0)
    weapon: str
    armor: str
    backstory: str


def generate_structured(prompt: str, model_class, max_retries: int = 3):
    """Generate JSON with Pydantic validation and self-healing retry."""
    schema_str = json.dumps(model_class.model_json_schema(), indent=2)
    messages = [{'role': 'user', 'content': (
        f'{prompt}\n\nRespond ONLY with valid JSON matching this schema:\n{schema_str}\n'
        'No markdown. No extra text. Valid JSON only.'
    )}]

    for attempt in range(1, max_retries + 1):
        raw = generate(messages, max_new_tokens=300, do_sample=False)
        clean = re.sub(r'^```json\s*|```$', '', raw.strip(), flags=re.MULTILINE).strip()
        try:
            return model_class(**json.loads(clean))
        except (json.JSONDecodeError, ValidationError) as e:
            print(f'  Attempt {attempt} failed: {e}')
            if attempt < max_retries:
                # Self-correction: tell model exactly what went wrong
                messages += [
                    {'role': 'assistant', 'content': clean},
                    {'role': 'user', 'content': f'Invalid JSON. Error: {e}. Fix and return ONLY valid JSON.'}
                ]
    return None


char = generate_structured('Create an interesting RPG character.', RPGCharacter)
if char:
    print('Validated character:')
    print(char.model_dump_json(indent=2))

"""---
# Section 6 — Context Engineering

> *"Context engineering is the delicate art and science of filling the context window with just the right information for the next step."* — Andrej Karpathy

## The Upgrade from Prompt Engineering

Prompt engineering optimizes *what you say*. Context engineering optimizes *everything the model knows when it speaks*.

```
CONTEXT WINDOW CONTENTS:
  [System Prompt] + [Memory] + [Retrieved Docs] + [History] + [Query]
      fixed          dynamic      dynamic           managed    current
```

## The 4 CE Strategies

| Strategy | What it does | Implementation |
|----------|-------------|----------------|
| **WRITE** | Save info outside the window | Memory DB, scratchpad |
| **SELECT** | Fetch only relevant info | RAG retrieval |
| **COMPRESS** | Reduce token footprint | Summarize old history |
| **ISOLATE** | Separate different contexts | Sub-agents, structured state |

"""

# --- Token budget tracking ---


# First step in CE: measure what you are actually spending.
# Most developers have no idea how many tokens their context consumes.

@dataclass
class ContextBudget:
    total_limit: int = 4096
    system_prompt: int = 500
    memory: int = 300
    retrieved_docs: int = 1500
    conversation: int = 1000
    query: int = 300
    response_reserve: int = 500

    def allocated(self) -> int:
        return self.system_prompt + self.memory + self.retrieved_docs + self.conversation + self.query + self.response_reserve

    def is_valid(self) -> bool:
        return self.allocated() <= self.total_limit


def count_tokens(text: str) -> int:
    return len(tokenizer.encode(text))


def audit_context(messages: list[dict], budget: ContextBudget) -> dict:
    """Audit token usage of an assembled context."""
    total = sum(count_tokens(m['content']) for m in messages)
    available = budget.total_limit - budget.response_reserve
    return {'total_tokens': total, 'available': available,
            'used_pct': f'{total/available*100:.1f}%', 'over_budget': total > available}


budget = ContextBudget()
print(f'Budget valid: {budget.is_valid()}')
print(f'Allocated: {budget.allocated()} / {budget.total_limit} tokens')

sample = [{'role': 'system', 'content': 'You are a helpful assistant. Answer only from provided context.'},
          {'role': 'user', 'content': 'What is our refund policy?'}]
print(f'Sample context audit: {audit_context(sample, budget)}')

# --- Conversation Manager: COMPRESS strategy ---

# Without management, history tokens grow linearly and hit the limit at ~turn 25.
# Pattern: keep last N turns in full, compress older turns into a summary.

class ConversationManager:
    """Sliding window history manager with automatic compression."""

    def __init__(self, max_full_turns: int = 6):
        self.max_full_turns = max_full_turns
        self.history: list[dict] = []
        self.summary: str = ''

    def add(self, role: str, content: str):
        self.history.append({'role': role, 'content': content})
        if len(self.history) > self.max_full_turns * 2:
            self._compress_oldest()

    def get_messages(self, system_prompt: str = '') -> list[dict]:
        msgs = []
        if system_prompt:
            msgs.append({'role': 'system', 'content': system_prompt})
        if self.summary:
            msgs.append({'role': 'system', 'content': f'[Earlier context]\n{self.summary}'})
        msgs.extend(self.history[-self.max_full_turns * 2:])
        return msgs

    def _compress_oldest(self):
        old = self.history[:-(self.max_full_turns * 2)]
        turn_text = '\n'.join(f"{t['role']}: {t['content']}" for t in old)
        new_summary = generate(
            [{'role': 'user', 'content': f'Summarize in 80 words, preserve all facts and decisions:\n\n{turn_text}'}],
            max_new_tokens=120, do_sample=False
        )
        self.summary = f'{self.summary}\n{new_summary}'.strip() if self.summary else new_summary.strip()
        self.history = self.history[-(self.max_full_turns * 2):]

    def token_count(self) -> int:
        return count_tokens(self.summary + ' '.join(t['content'] for t in self.history))


# Simulate a long conversation that would normally overflow
conv = ConversationManager(max_full_turns=3)
conv.add('user', 'My name is Priya and I am building a fraud detection system.')
conv.add('assistant', 'Great! Fraud detection typically uses anomaly detection or classification.')
conv.add('user', 'I am using Python and Kafka for real-time streaming.')
conv.add('assistant', 'Good choice. Kafka + Python is the industry standard for streaming pipelines.')
conv.add('user', 'What ML model would you recommend?')
conv.add('assistant', 'For real-time fraud, XGBoost or LightGBM are fast and accurate.')
conv.add('user', 'What tech stack did I mention earlier?')

print(f'Managed context token count: {conv.token_count()}')
reply = generate(conv.get_messages('You are a helpful ML assistant.'), max_new_tokens=80)
print(f'Reply: {reply}')

# --- Simple RAG: SELECT strategy ---

# Instead of stuffing ALL documents in the context (impossible),
# retrieve ONLY the relevant chunks at query time.
# In production: replace SentenceTransformers with a vector DB (FAISS, Chroma, Pinecone).

from sentence_transformers import SentenceTransformer
import numpy as np


class SimpleRAG:
    """Minimal RAG using sentence-transformers + cosine similarity."""

    def __init__(self, embedding_model: str = 'all-MiniLM-L6-v2'):
        self.embedder = SentenceTransformer(embedding_model)
        self.documents: list[str] = []
        self.embeddings = None

    def index(self, documents: list[str]):
        self.documents = documents
        self.embeddings = self.embedder.encode(documents, normalize_embeddings=True)
        print(f'Indexed {len(documents)} documents')

    def retrieve(self, query: str, top_k: int = 3):
        q_emb = self.embedder.encode([query], normalize_embeddings=True)
        scores = (q_emb @ self.embeddings.T).squeeze()
        top_idx = np.argsort(scores)[::-1][:top_k]
        return [(float(scores[i]), self.documents[i]) for i in top_idx]

    def answer(self, query: str, score_threshold: float = 0.3) -> str:
        chunks = [(s, d) for s, d in self.retrieve(query) if s >= score_threshold]
        if not chunks:
            context_block = 'No relevant documents found.'
        else:
            # Most relevant chunk FIRST — anti-lost-in-middle
            context_block = '\n\n'.join(f'[Source {i+1} | Score:{s:.2f}]\n{d}' for i,(s,d) in enumerate(chunks))
        system = f'Answer based only on provided context. If not in context, say so.\n\nContext:\n{context_block}'
        return generate([{'role': 'system', 'content': system}, {'role': 'user', 'content': query}], max_new_tokens=200)


# Build a tiny knowledge base about transformers
kb = [
    'The Transformer was introduced in Attention is All You Need (Vaswani et al., 2017).',
    'Self-attention allows each token to attend to every other token, capturing long-range dependencies.',
    'Positional encodings inject sequence order into the order-invariant attention mechanism.',
    'Multi-head attention runs several attention operations in parallel, each learning different patterns.',
    'BERT uses only the Transformer encoder for classification and QA tasks.',
    'GPT-style models use only the decoder with causal masking, generating text left-to-right.',
]

rag = SimpleRAG()
rag.index(kb)

query = 'What is multi-head attention and why is it useful?'
print(f'Query: {query}\n')
print(rag.answer(query))

print('\nTop retrieved chunks:')
for score, doc in rag.retrieve(query, top_k=2):
    print(f'  [{score:.3f}] {doc[:80]}...')

"""---
# Section 7 — The LLM Systems Landscape

## How all techniques fit together

| Technique | Optimizes | Requires Infra | Handles Live Data | Interview Depth |
|-----------|-----------|----------------|-------------------|-----------------|
| **Prompt Engineering** | The instruction | No | No | Entry |
| **Context Engineering** | Full info architecture | Minimal | Sometimes | Mid |
| **RAG** | Knowledge grounding | Vector DB | Yes | Mid-Senior |
| **Memory** | Cross-session continuity | Storage | Yes | Senior |
| **Structured Gen** | Output format | No | No | Mid |
| **Agents** | Multi-step execution | Orchestrator | Yes | Senior |

## Decision Framework

```
Needs private/live data?   Yes → RAG or Tool Use
Output must be parseable?  Yes → Structured Generation (Pydantic + constrained decoding)
Needs session memory?      Yes → Memory system (storage + selective recall)
Multi-step task?           Yes → Agentic workflow (ReAct, Plan-and-Execute)
Context window near limit? Yes → Context Engineering (compress + select)
None of the above?         Prompt Engineering is sufficient
```

## Advanced Tooling Reference

| Need | Tool | Why |
|------|------|-----|
| Orchestration | LangChain, LangGraph, LlamaIndex | Pre-built chains, agents, RAG |
| Structured output | Instructor, Outlines, Guidance | Constrained decoding |
| Vector DB | FAISS, Chroma, Pinecone, Qdrant | Scalable semantic search |
| Fast inference | vLLM, TGI, llama.cpp | 10-30x faster than HF pipeline |
| Experiment tracking | MLflow, W&B | Track prompts, metrics, costs |
| Evaluation | RAGAS, DeepEval, LangSmith | Automated quality measurement |

"""

# --- Technique selector: programmatic decision framework ---


def recommend_technique(requirements: dict) -> list[str]:
    """Map application requirements to the appropriate LLM techniques."""
    recs = ['Prompt Engineering']  # always the baseline
    if requirements.get('needs_private_or_live_data'):
        recs.append('RAG (Retrieval-Augmented Generation)')
    if requirements.get('output_must_be_parseable'):
        recs.append('Structured Generation (Pydantic + schema prompt)')
    if requirements.get('needs_session_memory'):
        recs.append('Memory System (vector DB + entity store)')
    if requirements.get('multi_step_reasoning'):
        recs.append('Chain-of-Thought or Tree-of-Thought')
    if requirements.get('autonomous_task_execution'):
        recs.append('Agentic Workflow (ReAct / Plan-and-Execute)')
    if requirements.get('context_window_near_limit'):
        recs.append('Context Engineering (compression + selective injection)')
    return recs


# Example: Customer support chatbot
print('=== Customer Support Chatbot ===')
for t in recommend_technique({'needs_private_or_live_data': True,
                               'output_must_be_parseable': True,
                               'needs_session_memory': True,
                               'context_window_near_limit': True}):
    print(f'  + {t}')

# Example: Research agent
print('\n=== Research Agent ===')
for t in recommend_technique({'needs_private_or_live_data': True,
                               'output_must_be_parseable': True,
                               'multi_step_reasoning': True,
                               'autonomous_task_execution': True,
                               'context_window_near_limit': True}):
    print(f'  + {t}')