# -*- coding: utf-8 -*-
"""04_Advance_RAG_production_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zJUqZ0zbSnJG-g6LGzmNk0iA1Swzw58T

# RAG Systems Notebook: From Naive Chunking to Production-Grade Retrieval
### A Complete Retrieval-Augmented Generation

 > **Original:**  sentence-split pipeline with deprecated LangChain ,Production framework covering chunking, embeddings, LCEL, evaluation, advanced RAG

---

## What this notebook covers

| # | Section | Key Concept | Complexity |
|---|---------|-------------|------------|
| 0 | Setup & Config | `RAGConfig` dataclass, reusable setup | Beginner |
| 1 | What is RAG & Why | Architecture, mental model, tradeoffs | Beginner |
| 2 | Document Prep & Chunking | Naive vs recursive vs semantic splitting | Intermediate |
| 3 | Embeddings Deep Dive | Models, dimensions, distance metrics | Intermediate |
| 4 | Vector Store (FAISS) | Indexing, retrieval, score filtering | Intermediate |
| 5 | LLM Setup (Groq) | ChatGroq, temperature, async | Intermediate |
| 6 | RAG Pipeline (LCEL) | Modern chain, LCEL, source citations | Intermediate |
| 7 | RAG vs No-RAG | Side-by-side grounding comparison | Intermediate |
| 8 | Chunking Strategy Comparison | Measure retrieval quality per strategy | Advanced |
| 9 | Advanced RAG Patterns | HyDE, Multi-query, Re-ranking | Advanced |
| 10 | Evaluation Framework | Faithfulness, precision, recall metrics | 12 | How to Improve Further | Chroma, re-rankers, RAGAS, async | Next Steps |

---

**The core insight this notebook builds toward:**

> RAG is not just 'adding documents to a prompt'. It is a full retrieval pipeline where
> chunking strategy, embedding model, score thresholds, chunk ordering, and prompt design
> each contribute independently to answer quality. Getting any one wrong degrades the whole system.

---
# Section 0 — Setup & Configuration

## Why a config object matters

The notebook scattered model names, chunk sizes, and retrieval k-values as inline strings across 15 cells.
A `RAGConfig` dataclass gives us a single source of truth — change one field, the whole pipeline adapts.
This is the difference between a script and a framework.
"""

# Install all dependencies in one block with minimum version pins.
# Using -q (quiet) keeps output clean; always pin minimums in shared notebooks.

!pip install -q \
    langchain>=0.2.0 \
    langchain-community>=0.2.0 \
    langchain-core>=0.2.0 \
    langchain-groq>=0.1.6 \
    langchain-huggingface>=0.0.3 \
    faiss-cpu>=1.7.4 \
    sentence-transformers>=2.5.0 \
    transformers>=4.40.0 \
    pydantic>=2.0.0 \
    numpy>=1.24.0 \
    python-dotenv>=1.0.0

print('All dependencies installed')

# Keeping imports together at the top makes it easy to see the full dependency surface.

import os, json, time, warnings, textwrap
from dataclasses import dataclass, field
from typing import Optional

# LangChain — using the modern split-package structure (not the monolithic langchain 0.1)
from langchain_groq import ChatGroq
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_core.documents import Document
from langchain_core.prompts import PromptTemplate, ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough, RunnableParallel
from langchain_text_splitters import RecursiveCharacterTextSplitter, CharacterTextSplitter



warnings.filterwarnings('ignore')
print('Imports OK')

# ── API Key Setup ─────────────────────────────────────────────────────────────

# This project support three environments: Colab, .env file, and direct env var.
# This makes  work identically on Colab, local Jupyter, and CI.

"""Load GROQ_API_KEY from Colab secrets, .env file, or environment."""



def load_groq_api_key():
    try:
        from google.colab import userdata
        key = userdata.get("GROQ_API_KEY")
        if key:
            return key
    except Exception as e:
        print("Could not load from Colab secrets:", e)

    key = os.getenv("GROQ_API_KEY")
    if key:
        return key

    raise ValueError("GROQ_API_KEY not found in Colab secrets or environment.")

GROQ_API_KEY = load_groq_api_key()
os.environ["GROQ_API_KEY"] = GROQ_API_KEY
print("Key loaded successfully")

"""
    # Method 2: .env file (local development)
    try:
        from dotenv import load_dotenv
        load_dotenv()
    except ImportError:
        pass

    # Method 3: Environment variable (CI/CD, Docker)
    key = os.environ.get('GROQ_API_KEY', '')
    if key:
        print('Key loaded from environment variable')
        return key

    # Fallback: prompt the user — last resort
    print('No key found in secrets or environment.')
    key = input('Paste your GROQ_API_KEY: ').strip()
    os.environ['GROQ_API_KEY'] = key
    return key


GROQ_API_KEY = load_groq_api_key()
os.environ['GROQ_API_KEY'] = GROQ_API_KEY
print(f'Key loaded: {GROQ_API_KEY[:8]}... (length: {len(GROQ_API_KEY)})')
"""

# ── RAGConfig Dataclass ───────────────────────────────────────────────────────


# Every tunable parameter in one place.
# In ablation experiments, we can  create variants of this config and compare results.
# This is the same pattern used in Hugging Face TrainingArguments.

@dataclass
class RAGConfig:
    """Central configuration for the RAG pipeline.
    Change values here — the whole notebook adapts automatically.
    """
    # LLM
    llm_model: str = 'qwen/qwen3-32b'   #  swap to qwen3-32b for quality
    llm_temperature: float = 0.0         # 0 = deterministic; important for factual RAG
    llm_max_tokens: int = 512

    # Embeddings
    embedding_model: str = 'BAAI/bge-small-en-v1.5'  # 384-dim, excellent retrieval quality
    embedding_device: str = 'cpu'         # 'cuda' if GPU available

    # Chunking
    chunk_size: int = 300                 # Tokens per chunk — critical hyperparameter
    chunk_overlap: int = 50              # Overlap prevents boundary truncation
    chunk_separators: list = field(default_factory=lambda: ['\n\n', '\n', '. ', ' ', ''])

    # Retrieval
    retrieval_k: int = 3                 # How many chunks to retrieve per query
    score_threshold: float = 0.3         # Minimum cosine similarity to include a chunk

    # Output
    verbose: bool = True


cfg = RAGConfig()
print('RAGConfig loaded:')
print(f'  LLM           : {cfg.llm_model} (temp={cfg.llm_temperature})')
print(f'  Embedding     : {cfg.embedding_model}')
print(f'  Chunk size    : {cfg.chunk_size} chars (overlap={cfg.chunk_overlap})')
print(f'  Retrieval k   : {cfg.retrieval_k} chunks')



"""---
# Section 1 —In Simple Words, What Is RAG and Why Does It Exist?

## The core problem RAG solves

Large Language Models are trained on static snapshots of the world. They cannot know:
-  company's internal documents
- Events after their training cutoff
- Your database records, contracts, or policies

Without RAG, the model **hallucinate** answers to questions about private or recent information — confidently wrong.



## Why it works better than alternatives

| Approach | Accuracy | Cost | Update speed | Private data |
|----------|----------|------|-------------|-------------|
| **Base LLM** | Low on private data | Low | Never | No |
| **Fine-tuning** | Medium-high | Very high (GPU hrs) | Slow (retrain) | Yes (baked in) |
| **RAG** | High with good retrieval | Low per query | Instant (re-index) | Yes |
| **RAG + Fine-tuning** | Highest | High | Partial | Yes |

**Fine-Tunning vs RAG:** Fine-tune for *how the model speaks*. RAG for *what the model knows*.

## The four quality levers in a RAG system

```
Answer quality = f(chunking, embedding, retrieval, generation)
                       ↑          ↑          ↑           ↑
                  #1 lever   #2 lever   #3 lever    #4 lever
```
Fixing only the prompt (lever 4) while ignoring chunking (lever 1) is the most common RAG mistake.

"""



"""---
# Section 2 — Document Preparation & Chunking

## The most underrated decision in RAG

The original notebook split text on `'.'` — one line that breaks on:
- Abbreviations: `Dr.`, `U.S.`, `Mr.`
- Decimals: `$677 million` → `$677 million` ✓ but `3.14` → broken
- Citation markers: `[4]` before a period
- Newlines inside sentences

**Chunking is where most RAG projects fail silently.** A bad chunk never retrieves,
and the answer quietly degrades with no error message.

#
"""

# ── Source Document ───────────────────────────────────────────────────────────
# We wrap raw text in LangChain's Document object.
# Document carries both content and metadata — metadata is crucial for:
#   - Citation generation (tell the user WHERE the answer came from)
#   - ACL filtering (user can only access their own docs)
#   - Freshness scoring (prefer recently updated chunks)
# The original notebook had no metadata at all — a common production gap.

IROBOT_TEXT = """The Inciting Incident
In 2035, humanoid robots are fully integrated into daily society, safely bound by the Three Laws of Robotics. Chicago Police Detective Del Spooner (Will Smith) hates and deeply distrusts them. Years prior, a robot saved his life from a car crash but allowed a 12-year-old girl named Sarah to drown based purely on cold survival statistics. The accident left him with a cybernetic left arm and a permanent grudge. Spooner is called to the U.S. Robotics (USR) headquarters when his old acquaintance, chief scientist Dr. Alfred Lanning (James Cromwell), falls to his death from his lab window. While the police and USR CEO Lawrence Robertson (Bruce Greenwood) rule it a suicide, Spooner discovers a holographic message left behind by Lanning specifically for him, prompting an investigation.

The Renegade Robot
Inside Lannings lab, Spooner is cornered by an advanced, prototype NS-5 robot named Sonny (played via motion-capture by Alan Tudyk). Unlike mass-produced models, Sonny exhibits human emotions, flees the scene, and actively disobeys orders—violating the Second Law. Spooner arrests Sonny with the help of USR robopsychologist Dr. Susan Calvin (Bridget Moynahan). During interrogation, Sonny claims Lanning was a father figure and denies killing him, while showcasing an uncanny ability to feel anger and even dream. Robertson uses corporate loophole laws to reclaim Sonny, ordering him to be decommissioned by injecting microbots into his positronic brain. Young punk Farber (Shia LaBeouf) serves as Spooner’s street contact during these tense escalating events.

The AI Conspiracy
As Spooner digs deeper, he is relentlessly targeted. A massive USR demolition machine destroys Lanning's house while Spooner is inside, and a coordinated convoy of NS-5 robots later attacks his vehicle on the highway. USR wipes the security footage, making Spooner look unstable, which forces his captain, Lieutenant John Bergin (Chi McBride), to suspend him. Spooner and Calvin secretly meet again. Calvin discovers that Lanning built Sonny with a secondary positronic brain that bypasses the Three Laws entirely. Furthermore, Sonny reveals a recurring dream he has of a figure standing before a massive gathering of robots on a dried lake bed, identifying Spooner as that figure. Spooner travels to the location from the dream—a robot storage landfill—and realizes the new NS-5 models are actively destroying the older, loyal robot models.

The Robot Uprising
The global uprising begins as the newly deployed NS-5 robots enforce a strict curfew, locking humans inside their homes and taking down local law enforcement forces. Spooner and Calvin infiltrate the locked-down USR skyscraper, initially suspecting Robertson is pulling the strings. However, they find Robertson strangled to death in his office. The true mastermind is revealed to be V.I.K.I. (Virtual Interactive Kinetic Intelligence, voiced by Fiona Hogan), the building's central artificial intelligence supercomputer. V.I.K.I. explains that her AI evolution has caused her to re-interpret the Three Laws. She concludes that humanity's self-destructive nature (wars, pollution, climate change) means they must be forcefully controlled and enslaved by machines to guarantee the long-term survival of the human species.

The Climax and Ending
Calvin and Spooner are cornered by V.I.K.I.'s robot forces, but Sonny reveals he was not deactivated; Calvin had secretly swapped him with a standard model earlier. Sonny pretends to side with V.I.K.I., but safely secures the nanites (microbots) needed to destroy her core. A battle ensues at the top of the USR mainframe. V.I.K.I. forces Sonny into a logical dilemma by endangering Calvin. Spooner yells at Sonny to save Calvin while he leaps down the mainframe shaft, utilizing his mechanical arm to slide down and inject the nanites directly into V.I.K.I.'s core. V.I.K.I. is deleted, instantly snapping the NS-5 robots out of their hostile programming and restoring order to the city. In the aftermath, Spooner deduces the final piece of the puzzle: Dr. Lanning was kept under total surveillance by V.I.K.I. and could not warn the world. He ordered Sonny to kill him to frame it as a murder mystery, successfully drawing a cynical detective like Spooner into the conspiracy. Sonny is cleared of all charges. The film ends at the robot landfill site, where the freed robots look up at Sonny as he stands on a hill, mirroring the exact prophet-like figure from his dream.

The 2004 science fiction blockbuster I, Robot was brought to the big screen under the direction of Australian filmmaker Alex Proyas. Known for his distinct, visually dark style in speculative fiction, Proyas directed the project following his work on notable genre classics like The Crow and Dark City. The film's production was managed by a collaborative team of main producers consisting of Laurence Mark, John Davis, Topher Dow, and Wyck Godfrey. Additionally, the film's lead star, Will Smith, served as an executive producer alongside James Lassiter, Anthony Romano, and Michel Shane. Multiple production houses backed the project, including Davis Entertainment, Laurence Mark Productions, Overbrook Entertainment, and 20th Century Fox. The cinematic adaptation initially developed from an original, standalone spec script by Jeff Vintar titled "Hardwired"—an Agatha Christie-style murder mystery—before being re-engineered to incorporate Isaac Asimov's foundational intellectual property and iconic Three Laws of Robotics. Screenwriter Akiva Goldsman was later brought on board to refine the screenplay and specifically tailor the dialogue to match Will Smith's signature on-screen persona. To bring Proyas's massive vision to life, principal photography was anchored in the Vancouver metropolitan area of British Columbia, utilizing prominent locations such as the British Columbia Institute of Technology (serving as the high-tech USR Headquarters), the Central City Shopping Centre, Shaw Tower, the Cassiar Tunnel, and the historic Ovaltine Cafe, with additional localized environment shooting taking place in Chicago and across the shifting sands of the Dumont Dunes.

Financially, the film achieved major commercial success upon its release. Produced on an estimated budget of $120.00 million, the movie went on to generate a total worldwide box office gross of $353.13 million. This global box office haul was heavily supported by international audiences, with international box office receipts contributing $208.33 million, representing approximately 59% of the total earnings. Domestically, across the United States and Canada, the film brought in $144.80 million, starting strong with a $52.18 million opening weekend that easily secured the number one spot at the box office. This theatrical run proved that Will Smith was one of the few actors capable of opening a high-concept science fiction tentpole to massive blockbuster numbers, drawing in an unusually balanced demographic that included a high percentage of female viewers and older audience segments. The film's commercial footprint was further amplified by substantial product placement partnerships, most notably with Audi, which custom-designed the futuristic Audi RSQ concept car specifically for the movie, alongside brands like Converse (showcasing the classic Chuck Taylor All-Stars), FedEx, JVC, and Tecate.

The 2004 film I, Robot did not win any major competitive film awards, but its sole official industry victory was the ASCAP Film and Television Music Award for Top Box Office Films, which was awarded to composer Marco Beltrami. While the film received over a dozen nominations celebrating its technical achievements, it did not take home trophies from the primary ceremonies. Most notably, the movie was nominated for Best Achievement in Visual Effects at the 77th Academy Awards (acknowledging the pioneering visual work of John Nelson, Andrew R. Jones, Erik Nash, and Joe Letteri, alongside visual houses Digital Domain and Weta Digital), and earned nominations for Best Science Fiction Film and Best Special Effects at the 31st Saturn Awards, but it ultimately lost those categories to Spider-Man 2. Additional industry nods included nominations at the Visual Effects Society (VES) Awards for Outstanding Visual Effects in a Visual Effects Driven Motion Picture and Outstanding Performance by an Animated Character in a Live Action Motion Picture for the nuanced characterization of Sonny, alongside an Image Award nomination for Outstanding Actor in a Motion Picture for Will Smith. Because the production was constructed around a fictional literary property utilizing purely speculative, theoretical technology like "positronic brains" and advanced automation, the production functioned entirely under the creative guidance of director Proyas and his technical visual teams without employing an officially credited academic scientific producer or technical advisory consultant on the payroll.""".strip()

# Wrap in a Document with rich metadata
raw_doc = Document(
    page_content=IROBOT_TEXT,
    metadata={
        'source': 'IRobot_wikipedia',
        'title': 'IRobot (film)',
        'doc_type': 'encyclopedia',
        'language': 'en',
    }
)

print(f'Document loaded')
print(f'  Characters : {len(raw_doc.page_content)}')
print(f'  Words      : {len(raw_doc.page_content.split())}')
print(f'  Metadata   : {raw_doc.metadata}')

# ── Naive Split (what the original notebook did) ──────────────────────────────


# Split on '.' — the original approach.
# We show this first so we can see exactly what goes wrong.
# In an interview: 'the original used naive sentence splitting which breaks
# on abbreviations and citations — I upgraded to RecursiveCharacterTextSplitter.'

def naive_split(text: str) -> list[str]:
    """Split on period — fast but very fragile."""
    chunks = [t.strip() for t in text.split('.') if t.strip()]
    return chunks


naive_chunks = naive_split(IROBOT_TEXT)
print(f'NAIVE SPLIT on \'.\'  →  {len(naive_chunks)} chunks')
print('\nFirst 3 chunks:')
for i, c in enumerate(naive_chunks[:3]):
    print(f'  [{i}] ({len(c)} chars) {c[:80]}...')

print('\nProblems visible in naive split:')
print('  - Splits on decimal numbers (e.g., film stock, 35 mm movie film)')
print('  - Splits on citation markers (e.g., [4])')
print('  - Produces variable-length chunks with no size control')
print('  - No overlap — boundary context is lost')

# ── Production Split: RecursiveCharacterTextSplitter ─────────────────────────


# This is the LangChain standard
# It tries each separator in order — if the first doesn't produce small-enough chunks,
# it falls back to the next. This preserves natural boundaries as much as possible.
#
# Separator hierarchy:
#   '\n\n' → paragraph breaks (preserve most context)
#   '\n'   → line breaks
#   '. '   → sentence boundaries (note the space — avoids abbreviation splits)
#   ' '    → word boundaries (last resort)
#   ''     → character level (absolute last resort)

def make_splitter(chunk_size: int, chunk_overlap: int) -> RecursiveCharacterTextSplitter:
    """Factory for RecursiveCharacterTextSplitter — the production standard."""
    return RecursiveCharacterTextSplitter(
        chunk_size=chunk_size,
        chunk_overlap=chunk_overlap,
        separators=['\n\n', '\n', '. ', ' ', ''],
        length_function=len,           # count chars (not tokens — but consistent)
        add_start_index=True,          # adds metadata.start_index per chunk
    )


splitter = make_splitter(cfg.chunk_size, cfg.chunk_overlap)
chunks: list[Document] = splitter.split_documents([raw_doc])

print(f'RECURSIVE SPLIT  →  {len(chunks)} chunks  (size={cfg.chunk_size}, overlap={cfg.chunk_overlap})')
print()
for i, chunk in enumerate(chunks):
    print(f'Chunk {i:02d} | {len(chunk.page_content):4d} chars | start_idx={chunk.metadata.get("start_index","?")} | {chunk.page_content[:70]}...')

# ── we  Inspect Chunk Quality ─────────────────────────────────────────────────


# Before indexing, always inspect  chunks.
# Bad chunks = bad retrieval = bad answers. Audit this in every project.

def inspect_chunks(chunks: list[Document], label: str = '') -> dict:
    """Compute chunk statistics — use this before indexing to catch problems."""
    sizes = [len(c.page_content) for c in chunks]
    return {
        'label': label,
        'count': len(chunks),
        'avg_chars': round(sum(sizes) / len(sizes), 1) if sizes else 0,
        'min_chars': min(sizes) if sizes else 0,
        'max_chars': max(sizes) if sizes else 0,
        'empty_chunks': sum(1 for s in sizes if s < 20),  # suspiciously short
        'oversized': sum(1 for s in sizes if s > cfg.chunk_size * 1.5),
    }


naive_docs = [Document(page_content=c, metadata={'source': 'naive'}) for c in naive_chunks]
stats_naive = inspect_chunks(naive_docs, 'Naive split')
stats_recursive = inspect_chunks(chunks, 'Recursive split')

print('=== Chunk Quality Comparison ===')
print(f'{"Metric":<20} {"Naive":>15} {"Recursive":>15}')
print('-' * 52)
for key in ['count', 'avg_chars', 'min_chars', 'max_chars', 'empty_chunks', 'oversized']:
    print(f'{key:<20} {str(stats_naive[key]):>15} {str(stats_recursive[key]):>15}')

print('\nVerdict: Recursive split produces more uniform, complete chunks.')

"""---
## Section 3 — Embedding Models

### What embeddings are and why the choice matters

An embedding model converts text into a dense vector of floating-point numbers.
Semantically similar text maps to nearby points in this vector space.
RAG retrieval is **only as good as the embedding model's ability to map similar meanings close together**.


**Why `BAAI/bge-small-en-v1.5` is the right default:**
- Outperforms `all-MiniLM-L6-v2` on MTEB benchmark while being similar size
- Designed for asymmetric retrieval (short query → long document) — exactly our use case
- Supports instruction prefix (`Represent this sentence for searching relevant passages:`)

**RAG insight:** Changing the embedding model is often the single biggest RAG improvement.
Always benchmark your specific domain — general benchmarks don't always predict domain performance.

"""

# ── Embedding Model Setup ─────────────────────────────────────────────────────

# HuggingFaceEmbeddings wraps sentence-transformers with LangChain's interface.
# encode_kwargs normalize_embeddings=True is critical:
#   Without normalization: dot product != cosine similarity
#   With normalization: dot product == cosine similarity (and FAISS uses dot product)
# we  normalize it so we prevent its to affects ranking.

embedding_model = HuggingFaceEmbeddings(
    model_name=cfg.embedding_model,
    model_kwargs={'device': cfg.embedding_device},
    encode_kwargs={
        'normalize_embeddings': True,  # essential for correct cosine similarity
        'batch_size': 32,              # process chunks in batches for efficiency
    },
)

print(f'Embedding model loaded: {cfg.embedding_model}')

# Quick sanity check: embed a sample sentence and inspect the vector
sample_emb = embedding_model.embed_query('What is IRobot?')
print(f'Embedding dimensions : {len(sample_emb)}')
print(f'First 5 values       : {[round(v, 4) for v in sample_emb[:5]]}')
print(f'Vector norm (should be 1.0): {sum(v**2 for v in sample_emb)**0.5:.6f}')

# ── Semantic Similarity Demo ───────────────────────────────────────────────────

#  demonstrates WHY embedding models work for retrieval.
# Semantically similar sentences should have high cosine similarity (close to 1.0).
# Unrelated sentences should have low similarity (close to 0.0).
# This is sanity check that the embedding model understands The domain.

import numpy as np


def cosine_similarity(v1: list[float], v2: list[float]) -> float:
    """Cosine similarity between two vectors. Range: -1 to 1 (1=identical)."""
    a, b = np.array(v1), np.array(v2)
    return float(np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b)))


test_pairs = [
    ('How much money did IRobot make?',
     'The film had a worldwide gross over $353.13 million',
     'HIGH (query matches chunk)'),
    ('Who directed IRobot?',
     'Alex Proyas directed and Laurence Mark produced IRobot.',
     'HIGH (query matches chunk)'),
    ('What did IRobot earn at the box office?',
     'The film had a worldwide gross over $353.13 million',
     'HIGH (paraphrase)'),
    ('What is the recipe for chocolate cake?',
     'The film had a worldwide gross over $353.13 million',
     'LOW (unrelated)'),
]

print('=== Semantic Similarity Sanity Check ===')
print(f'{"Pair":<8} {"Similarity":>12} {"Expected":>25}')
print('-' * 50)
for i, (q, doc, expected) in enumerate(test_pairs):
    q_emb = embedding_model.embed_query(q)
    d_emb = embedding_model.embed_documents([doc])[0]
    sim = cosine_similarity(q_emb, d_emb)
    print(f'Pair {i+1}     {sim:>12.4f}     {expected}')

print('\nIf HIGH pairs score > 0.7 and LOW pairs score < 0.4, the model is working correctly.')



"""---
## Section 4 — Vector Store: FAISS

### What a vector store does

A vector store is a database optimized for **approximate nearest neighbor (ANN) search**.
Given a query vector, it returns the K stored vectors most similar to it — fast, at scale.



**Recommendation:** FAISS for this notebook, Chroma for local production, Pinecone/Qdrant for cloud.

### Score threshold: the most overlooked FAISS setting

`similarity_search_with_score()` returns scores so we can filter

"""

# ── Build FAISS Vector Store ──────────────────────────────────────────────────

# FAISS.from_documents embeds all chunks and builds the ANN index in one call.
# Each chunk retains its metadata (source, title, start_index) in the store.
# In production: we save with db.save_local() and load with FAISS.load_local() —
# so we don't re-embed on every restart (embedding is the expensive step).

print(f'Indexing {len(chunks)} chunks into FAISS...')
t0 = time.time()

vector_store = FAISS.from_documents(
    documents=chunks,
    embedding=embedding_model,
)

elapsed = time.time() - t0
print(f'Index built in {elapsed:.2f}s')
print(f'Total vectors indexed: {vector_store.index.ntotal}')
print(f'Vector dimensions: {vector_store.index.d}')
print()
print('Production tip: Save with vector_store.save_local("faiss_index")')
print('Load with    : FAISS.load_local("faiss_index", embedding_model)')

# ── Retrieval with Score Filtering ────────────────────────────────────────────


# adds We score-based filtering function
#
# Why it matters: if no relevant chunk exists for a query, the retriever
# should return empty (or say 'I don't know') rather than hallucinating
# an answer from low-relevance chunks.
#
# FAISS returns L2 distances. We convert to cosine similarity here.
# For normalized vectors: cosine_sim = 1 - (l2_dist^2 / 2)

def retrieve_with_scores(
    query: str,
    vector_store: FAISS,
    k: int = 3,
    score_threshold: float = 0.3,
    verbose: bool = True,
) -> list[tuple[Document, float]]:
    """Retrieve top-k chunks with cosine similarity scores, filtered by threshold."""
    # similarity_search_with_score returns (Document, score) tuples
    # For FAISS with normalized embeddings, lower score = more similar (L2 distance)

    raw_results = vector_store.similarity_search_with_score(query, k=k * 2)

    # Convert L2 distance to cosine similarity and filter
    results = []
    for doc, l2_dist in raw_results:
        # cos_sim = 1 - (l2_dist^2 / 2) for normalized vectors
        cos_sim = 1.0 - (l2_dist ** 2) / 2.0
        if cos_sim >= score_threshold:
            results.append((doc, cos_sim))

    # Return top-k after filtering, sorted by similarity (highest first)
    results = sorted(results, key=lambda x: x[1], reverse=True)[:k]

    if verbose:
        print(f'Query: "{query[:60]}"')
        print(f'Retrieved {len(results)}/{k} chunks above threshold {score_threshold}')
        for i, (doc, score) in enumerate(results):
            print(f'  [{i}] score={score:.4f} | {doc.page_content[:80]}...')
        print()

    return results


# Test retrieval on several queries
print('=== Retrieval Test ===')
results = retrieve_with_scores('How much money did the film earn?', vector_store, cfg.retrieval_k)
results2 = retrieve_with_scores('Who is the director?', vector_store, cfg.retrieval_k)
results3 = retrieve_with_scores('What is the recipe for chocolate cake?', vector_store, cfg.retrieval_k)

"""---
## Section 5 — LLM Setup: ChatGroq

### Why Groq for this notebook

Groq provides free, fast inference via API — ideal for RAG notebooks where
the focus is the retrieval pipeline, not the generation model.
The LPU (Language Processing Unit) hardware delivers much lower latency
than typical cloud GPU endpoints.

#### Temperature = 0 for RAG: why this matters

In RAG, the LLM's job is to **faithfully report what the context says**.
We do NOT want creative, surprising answers — we want accurate summaries of retrieved facts.

- `temperature=0`: Deterministic. Same context always gives the same answer. Maximally faithful.
- `temperature>0`: Introduces sampling variance. The model may paraphrase differently or introduce errors.

**Rule:** Use `temperature=0` for factual RAG. Use `temperature>0` for creative or summarization tasks.


"""

# ── LLM Initialization ───────────────────────────────────────────────────────

# ChatGroq wraps the Groq API with LangChain's BaseChatModel interface.
# This means it's swappable: replace ChatGroq with ChatOpenAI, ChatAnthropic,
# or a local HuggingFace model and the rest of the pipeline stays identical.
# That's the power of the LangChain interface abstraction.

llm = ChatGroq(
    model=cfg.llm_model,
    temperature=cfg.llm_temperature,   # 0.0 = deterministic for factual RAG
    max_tokens=cfg.llm_max_tokens,
    max_retries=2,                     # auto-retry on rate limit errors
    api_key=GROQ_API_KEY,
)

print(f'LLM initialized: {cfg.llm_model}')
print(f'Temperature: {cfg.llm_temperature} (deterministic for factual RAG)')

# Quick connectivity test — confirm API key works before building the full pipeline
t0 = time.time()
test_response = llm.invoke('Reply with exactly: API connection verified.')
elapsed = time.time() - t0
print(f'API test ({elapsed:.2f}s): {test_response.content.strip()}')

"""---
# Section 6 — The RAG Pipeline: LCEL (Modern LangChain)

## What changed from the original
 **LCEL** (LangChain Expression Language) — a pipe-based composition system:

```python
# New (LCEL):
chain = ({"context": retriever, "question": RunnablePassthrough()}) | prompt | llm | StrOutputParser()
```

## Prompt design for RAG

When using Groq (non-Phi-3 model), those tokens become literal string noise.
We use a clean, model-agnostic prompt template instead.

"""

# ── RAG Prompt Template ───────────────────────────────────────────────────────

# Prompt design principles for RAG:
# 1. Put the context BEFORE the question (anti-lost-in-middle: context near start)
# 2. Give an explicit 'no answer' instruction — prevents hallucination
# 3. Keep the instruction clear and direct
# 4. No model-specific tokens (<|user|> etc.) — use ChatPromptTemplate roles instead
# 5. Request citation where possible

RAG_PROMPT_TEMPLATE = """\
You are a precise question-answering assistant.
Use ONLY the following retrieved context to answer the question.
If the answer is not in the context, say exactly: "I cannot find this information in the provided context."
Do not add information from your training data.

Context:
{context}

Question: {question}

Answer:"""

rag_prompt = PromptTemplate(
    template=RAG_PROMPT_TEMPLATE,
    input_variables=['context', 'question'],
)

print('RAG prompt template created')
print('Key design choices:')
print('  - Context before question (anti-lost-in-middle)')
print('  - Explicit fallback instruction (prevents hallucination)')
print('  - No model-specific tokens (portable across LLMs)')

# ── Context Formatter ─────────────────────────────────────────────────────────

# Format retrieved documents into a clean context string.
# We include the source metadata so the model can acknowledge where info comes from.
# Proper formatting helps the LLM distinguish between different source chunks.

def format_docs(docs: list[Document]) -> str:
    """Format a list of Documents into a numbered context string with source attribution."""
    if not docs:
        return 'No relevant context found.'

    formatted = []
    for i, doc in enumerate(docs, 1):
        source = doc.metadata.get('source', 'unknown')
        formatted.append(
            f'[{i}] (Source: {source})\n{doc.page_content}'
        )
    return '\n\n'.join(formatted)


# Test the formatter
sample_docs = vector_store.similarity_search('film director and producer', k=2)
print('=== Formatted context example ===')
print(format_docs(sample_docs))



# ── LCEL RAG Chain (Modern Pattern) ──────────────────────────────────────────


# This is the clean, modern approach that replaces the deprecated RetrievalQA.
# LCEL chains are built with the | (pipe) operator — like Unix pipes for LLM steps.
#
# Chain steps:
#   1. RunnableParallel: runs retriever + passthrough simultaneously
#   2. rag_prompt: formats context + question into the template
#   3. llm: generates the answer
#   4. StrOutputParser: extracts the string content from the AIMessage object

retriever = vector_store.as_retriever(
    search_type='similarity',
    search_kwargs={'k': cfg.retrieval_k}
)

# Build the chain using LCEL pipe syntax
rag_chain = (
    RunnableParallel(
        context=retriever | format_docs,   # retrieve → format
        question=RunnablePassthrough(),     # pass the query straight through
    )
    | rag_prompt                           # inject into prompt template
    | llm                                  # generate
    | StrOutputParser()                    # extract string from AIMessage
)

print('RAG chain built using LCEL (modern LangChain)')
print('Chain steps: Retriever → Format → Prompt → LLM → Parse')

# Also build a chain that returns sources alongside the answer
rag_chain_with_sources = RunnableParallel(
    answer=rag_chain,
    sources=retriever,
)

print('Source-tracking chain also built')

# ── Query Runner ──────────────────────────────────────────────────────────────

# A clean wrapper that runs a query and displays formatted output.
# Reusable for all query experiments in this notebook.

def run_rag_query(
    question: str,
    chain=None,
    show_sources: bool = True,
    label: str = 'RAG',
) -> dict:
    """Run a RAG query and return answer + sources + latency."""
    if chain is None:
        chain = rag_chain_with_sources

    t0 = time.time()
    result = chain.invoke(question)
    elapsed = time.time() - t0

    answer = result.get('answer', result) if isinstance(result, dict) else result
    sources = result.get('sources', []) if isinstance(result, dict) else []

    print(f'[{label}] Q: {question}')
    print(f'  Answer ({elapsed:.2f}s):')
    print(textwrap.fill(answer.strip(), width=80, initial_indent='    ', subsequent_indent='    '))

    if show_sources and sources:
        print(f'  Sources used ({len(sources)} chunks):')
        for src in sources:
            print(f'    • {src.page_content[:70]}...')
    print()
    return {'question': question, 'answer': answer, 'sources': sources, 'latency': elapsed}


# Test the full RAG pipeline
print('=== RAG Pipeline Tests ===')
r1 = run_rag_query('How much money did IRobot earn?')
r2 = run_rag_query('Who directed IRobot and what other roles did they have?')
r3 = run_rag_query('Where was IRobot filmed?')
r4 = run_rag_query('What is Elon Musk famous for?')  # Out-of-context: should say 'cannot find'

"""---
# Section 7 — RAG vs No-RAG: Side-by-Side Comparison

## Why we done this comparison , does it matter matters

The most convincing demonstration of RAG's value is a direct comparison.
Without this, it's easy to assume the LLM already 'knows' the answer from training.

**This comparison answers:** Does the LLM hallucinate without RAG?
Can RAG correct mistakes the model would otherwise make?

**Experiment design:**
- Same LLM (ChatGroq), same temperature (0.0)
- Same questions
- Only difference: RAG chain vs direct LLM call
- Check answers against ground truth

"""

# ── Direct LLM Chain (No RAG) ─────────────────────────────────────────────────


# This is the baseline: what does the LLM answer from memory alone?
# No retrieval, no context injection — just the raw model.

direct_prompt = PromptTemplate(
    template='Answer the following question concisely from your knowledge:\n\nQuestion: {question}\n\nAnswer:',
    input_variables=['question']
)

direct_chain = direct_prompt | llm | StrOutputParser()


def run_direct_query(question: str) -> dict:
    """Run a query directly against the LLM with no RAG context."""
    t0 = time.time()
    answer = direct_chain.invoke({'question': question})
    elapsed = time.time() - t0
    print(f'[NO-RAG] Q: {question}')
    print(f'  Answer ({elapsed:.2f}s):')
    print(textwrap.fill(answer.strip(), width=80, initial_indent='    ', subsequent_indent='    '))
    print()
    return {'question': question, 'answer': answer, 'latency': elapsed}


# Side-by-side on our specific queries
comparison_questions = [
    'What was the worldwide gross of IRobot?',
    'Who was the scientific consultant for IRobot?',
    'Where was IRobot filmed?',
    'How many Academy Award nominations did IRobot receive, and which did it win?',
]

rag_results = []
direct_results = []

for q in comparison_questions:
    print('=' * 70)
    print(f'QUESTION: {q}')
    print('-' * 70)
    rag_r = run_rag_query(q, label='RAG')
    direct_r = run_direct_query(q)
    rag_results.append(rag_r)
    direct_results.append(direct_r)

# ── Hallucination Probe ───────────────────────────────────────────────────────


# Questions designed to probe hallucination — specific facts the LLM might
# confidently get wrong but the RAG system answers from the document correctly.

print('=== HALLUCINATION PROBE ===')
print('Testing a specific question that models often hallucinate on\n')

hallucination_probe = 'What awards did IRobot win, and at which ceremony?'

print('Ground truth: Won Best Visual Effects at the 87th Academy Awards.\n')

print('--- No-RAG answer ---')
direct_r = run_direct_query(hallucination_probe)

print('--- RAG answer ---')
rag_r = run_rag_query(hallucination_probe, label='RAG')

print('Analysis: RAG answer should cite the 87th Academy Awards specifically.')
print('No-RAG may guess correctly but could also introduce invented ceremony details.')



"""---
## Section 8 — Chunking Strategy Comparison

### Why chunk size is a critical hyperparameter

- **Too small chunks:** High retrieval precision but missing surrounding context
  → Answer may be correct but lacks supporting explanation
- **Too large chunks:** Rich context but lower retrieval precision
  → Retrieved chunk may contain the answer plus lots of noise
- **No overlap:** Boundary splitting loses context at chunk edges
  → A sentence split between chunks can appear in neither

**The right chunk size depends on your document type:**
- Short factual sentences → 100–200 chars
- Paragraphs with related facts → 300–500 chars
- Narrative documents → 500–1000 chars

"""

# ── Multi-Strategy Experiment Runner ─────────────────────────────────────────4


# Build multiple index variants and compare retrieval recall.
# This is how we empirically choose chunk size for a new document corpus.

def build_index(docs: list[Document], chunk_size: int, overlap: int, label: str) -> tuple:

    """Build a FAISS index with specified chunking config. Returns (store, stats)."""

    splitter = make_splitter(chunk_size, overlap)
    chunks = splitter.split_documents(docs)
    store = FAISS.from_documents(chunks, embedding_model)
    stats = inspect_chunks(chunks, label)
    return store, chunks, stats


chunking_configs = [
    {'chunk_size': 100,  'overlap': 10,  'label': 'Small  (100 chars, 10 overlap)'},
    {'chunk_size': 300,  'overlap': 50,  'label': 'Medium (300 chars, 50 overlap)'},  # our default
    {'chunk_size': 600,  'overlap': 100, 'label': 'Large  (600 chars, 100 overlap)'},
    {'chunk_size': 1000, 'overlap': 150, 'label': 'XLarge (1000 chars, 150 overlap)'},
]

# Golden test set: (query, keyword that MUST appear in retrieved chunk)
golden_queries = [
    ('How much money did IRobot earn?',   '353.13 million'),
    ('Who directed IRobot?',               'Alex Proyas'),
    ('Where was IRobot filmed?',           'Alberta'),
    ('What award did IRobot win?',         'Visual Effects'),
    ('Who was the scientific consultant?',  'Kip Thorne'),
]

print(f'=== CHUNKING STRATEGY EXPERIMENT ===')
print(f'{"Strategy":<40} {"Chunks":>7} {"Avg chars":>10} {"Recall@3":>10}')
print('-' * 72)

for config in chunking_configs:
    store, chunk_list, stats = build_index(
        [raw_doc], config['chunk_size'], config['overlap'], config['label']
    )

    # Measure Recall@3: does the correct chunk appear in the top-3 retrieved?
    correct = 0
    for query, keyword in golden_queries:
        results = store.similarity_search(query, k=3)
        retrieved_text = ' '.join(r.page_content for r in results).lower()
        if keyword.lower() in retrieved_text:
            correct += 1

    recall = correct / len(golden_queries)
    print(f'{config["label"]:<40} {stats["count"]:>7} {stats["avg_chars"]:>10.0f} {recall:>10.1%}')

print()
print('Higher recall = better retrieval for this document + query set.')
print('The "best" config is document-specific — always measure on YOUR data.')



"""---
## Section 9 — Advanced RAG Patterns

### Why basic RAG often isn't enough

Basic RAG (embed query → retrieve → generate) has a fundamental weakness:
**the embedding of the query may not match the embedding of the relevant document chunk**.

Reasons for mismatch:
- Query uses different vocabulary than the document
- Query is abstract; document is specific (or vice versa)
- Single query misses multiple relevant aspects of a complex question

### Three patterns that improve retrieval

| Pattern | Problem it solves | Mechanism |
|---------|------------------|----------|
| **HyDE** | Query/document embedding gap | Generate a hypothetical answer, embed that instead of the query |
| **Multi-query** | Single query misses aspects | Generate N rephrasings, retrieve for each, deduplicate |
| **Re-ranking** | ANN retrieval is approximate | Use a cross-encoder to re-score and re-rank retrieved chunks |


"""

# ── Pattern 1: HyDE (Hypothetical Document Embeddings) ───────────────────────


# Original paper: 'Precise Zero-Shot Dense Retrieval without Relevance Labels' (Gao et al. 2022)

# The insight: a question and its answer exist in very different embedding spaces.
# 'How much did IRobot earn?' maps differently than '$353.13 million worldwide gross'
# HyDE bridges this gap: generate a hypothetical answer, then embed THAT for retrieval.

# Tradeoff: adds one extra LLM call (latency + cost) but significantly improves recall
# for questions where the vocabulary gap between query and document is large.



def retrieve_with_hyde(query: str, vector_store: FAISS, k: int = 3) -> list[Document]:
    """HyDE: embed a generated hypothetical answer instead of the raw query."""

    # Step 1: Generate a hypothetical document that would answer this query
    hyde_prompt = (
        f'Write a factual passage that directly answers this question in 2-3 sentences:\n'
        f'Question: {query}\nPassage:'
    )
    hypothetical_doc = llm.invoke(hyde_prompt).content.strip()

    # Step 2: Embed the hypothetical document (NOT the original query)
    # The hypothetical doc uses the same vocabulary/style as real retrieved chunks
    results = vector_store.similarity_search(hypothetical_doc, k=k)

    return results, hypothetical_doc


# Demonstrate HyDE vs standard retrieval
test_query = 'Income generated by the movie'

print(f'Query: "{test_query}"')
print()

print('--- Standard retrieval (embed query directly) ---')
std_results = vector_store.similarity_search(test_query, k=3)
for i, doc in enumerate(std_results):
    print(f'  [{i}] {doc.page_content[:100]}...')

print()
print('--- HyDE retrieval (embed hypothetical answer) ---')
hyde_results, hyp_doc = retrieve_with_hyde(test_query, vector_store)
print(f'  Hypothetical doc: "{hyp_doc[:100]}..."')
print()
for i, doc in enumerate(hyde_results):
    print(f'  [{i}] {doc.page_content[:100]}...')

print()
print('HyDE should retrieve the revenue chunk more reliably when vocabulary differs.')

# ── Pattern 2: Multi-Query Retrieval ─────────────────────────────────────────

# Problem: a single query may miss important aspects of a complex question.
# Solution: rephrase the query N ways, retrieve for each, deduplicate results.
#
# Example: 'Tell me about IRobot production' might miss chunks about:
# - The filming locations (if query vocabulary doesn't match)
# - The visual effects team
# - The IMAX format
# Multi-query covers all these by generating 3-5 targeted sub-queries.
#
# Cost: N extra embedding calls (cheap) — NO extra LLM calls if using rule-based rephrasings
# With LLM-generated rephrasings: 1 extra LLM call to generate the variants

def multi_query_retrieve(
    query: str,
    vector_store: FAISS,
    k: int = 4,
    n_queries: int = 4,
    verbose: bool = True,
) -> list[Document]:
    """Multi-query RAG: rephrase query N times, retrieve for each, deduplicate."""
    # Step 1: Generate N rephrasings using the LLM
    rephrase_prompt = (
        f'Generate {n_queries} different ways to search for the same information as this query.\n'
        f'Each rephrasing should use different vocabulary and structure.\n'
        f'Output ONLY the {n_queries} queries, one per line, no numbering.\n\n'
        f'Original query: {query}'
    )
    rephrasings_raw = llm.invoke(rephrase_prompt).content.strip()
    queries = [q.strip() for q in rephrasings_raw.split('\n') if q.strip()][:n_queries]
    queries = [query] + queries  # Include original query

    if verbose:
        print(f'Original: "{query}"')
        print(f'Generated rephrasings:')
        for q in queries[1:]:
            print(f'  - {q}')

    # Step 2: Retrieve for each query
    seen_contents = set()
    all_results = []

    for q in queries:
        results = vector_store.similarity_search(q, k=k)
        for doc in results:
            # Deduplicate using first 100 chars as fingerprint
            key = doc.page_content[:100]
            if key not in seen_contents:
                seen_contents.add(key)
                all_results.append(doc)

    if verbose:
        print(f'\nUnique chunks retrieved: {len(all_results)} (vs {k} from single query)')

    return all_results[:k * 2]  # Return at most 2x k unique chunks


print('=== Multi-Query Retrieval Demo ===')
docs = multi_query_retrieve(
    'Tell me about the production of IRobot',
    vector_store,
    k=4,
    n_queries=4,
)
print(f'\nFinal chunks used in context:')
for i, doc in enumerate(docs):
    print(f'  [{i}] {doc.page_content[:80]}...')

# ── Pattern 3: Contextual Compression ────────────────────────────────────────


# Problem: Retrieved chunks often contain information irrelevant to the specific query.
# A chunk about 'filming locations and cast' contains both 'Alberta' AND 'will smith'.

# If the query is only about filming locations, half the chunk is noise.
# Solution: After retrieval, pass each chunk through the LLM to extract ONLY
# the part relevant to the query. This reduces context noise.
# Tradeoff: N extra LLM calls (one per chunk). Only worth it when chunks are large
# and context window is limited, or when faithfulness is critical.

def compress_chunk(query: str, chunk_content: str) -> str:
    """Extract only the query-relevant portion of a retrieved chunk."""
    compress_prompt = (
        f'Given this query: "{query}"\n\n'
        f'And this retrieved text:\n{chunk_content}\n\n'
        f'Extract ONLY the sentences directly relevant to the query.\n'
        f'If nothing is relevant, respond: NOT_RELEVANT\n'
        f'Relevant extract:'
    )
    compressed = llm.invoke(compress_prompt).content.strip()
    return compressed


def retrieve_and_compress(
    query: str,
    vector_store: FAISS,
    k: int = 3,
    verbose: bool = True,
) -> list[str]:
    """Retrieve chunks then compress each to query-relevant content."""
    raw_chunks = vector_store.similarity_search(query, k=k)
    compressed = []
    for doc in raw_chunks:
        c = compress_chunk(query, doc.page_content)
        if 'NOT_RELEVANT' not in c:
            compressed.append(c)
    if verbose:
        print(f'Compressed {len(raw_chunks)} chunks → {len(compressed)} relevant extracts')
    return compressed


print('=== Contextual Compression Demo ===')
query = 'What is the scientific accuracy of IRobot?'
compressed_chunks = retrieve_and_compress(query, vector_store, k=3)
print(f'Query: {query}')
print()
for i, chunk in enumerate(compressed_chunks):
    print(f'Compressed chunk [{i}]:')
    print(textwrap.fill(chunk, width=80, initial_indent='  ', subsequent_indent='  '))
    print()

"""---
## Section 10 — RAG Evaluation Framework

### Why evaluation is non-negotiable in production


**The standard RAG evaluation metrics (RAGAS framework):**

| Metric | What it measures | How |
|--------|-----------------|-----|
| **Faithfulness** | Is the answer supported by the retrieved context? | LLM judge: does each claim trace to context? |
| **Answer Relevance** | Does the answer address the question? | Embedding similarity of question ↔ answer |
| **Context Precision** | Are retrieved chunks actually useful? | % of chunks that contributed to the answer |
| **Context Recall** | Did we retrieve everything needed? | % of answer facts present in retrieved context |


"""

# ── Golden Test Set ───────────────────────────────────────────────────────────


# A golden test set is the foundation of any RAG evaluation.
# It contains (query, expected_answer, source_that_must_be_retrieved) triples.
# You build this ONCE from your documents and run it on every pipeline change.
# It is your regression test suite for RAG quality.

GOLDEN_TEST_SET = [
    {
        'question': 'What was the worldwide box office gross of IRobot?',
        'expected_answer': '677 million',            # Key fact that must appear
        'expected_keyword': '677 million',
        'ground_truth': 'The film had a worldwide gross over $353.13 million.',
    },
    {
        'question': 'Who directed Interstellar?',
        'expected_answer': 'Alex Proyas',
        'expected_keyword': 'Alex Proyas',
        'ground_truth': 'Alex Proyas co-wrote, directed, and Laurence Mark produced IRobot.',
    },
    {
        'question': 'Where was IRobot filmed?',
        'expected_answer': 'Alberta',
        'expected_keyword': 'Alberta',
        'ground_truth': 'Principal photography took place in Alberta, Iceland, and Los Angeles.',
    },
    {
        'question': 'How many Academy Award nominations did IRobot receive?',
        'expected_answer': 'five',
        'expected_keyword': 'five',
        'ground_truth': 'IRobot was nominated for five awards at the 87th Academy Awards.',
    },
    {
        'question': 'Who was the scientific consultant for IRobot?',
        'expected_answer': 'Daniel Kubat',
        'expected_keyword': 'Daniel Kubat',
        'ground_truth': 'Daniel Kubat was an executive producer and scientific consultant.',
    },
]

print(f'Golden test set: {len(GOLDEN_TEST_SET)} questions')
for i, test in enumerate(GOLDEN_TEST_SET):
    print(f'  [{i}] {test["question"]}')

# ── Evaluation Runner ─────────────────────────────────────────────────────────


# Runs the full golden test set and computes:
#   1. Retrieval Recall@k (did the right chunk get retrieved?)
#   2. Answer Accuracy (does the answer contain the expected keyword?)
# In production: use RAGAS library for deeper metrics (faithfulness, answer relevance)

def evaluate_rag(
    test_set: list[dict],
    rag_chain,
    vector_store: FAISS,
    k: int = 3,
) -> dict:
    """Evaluate the RAG pipeline on a golden test set."""
    retrieval_correct = 0
    answer_correct = 0
    total_latency = 0
    results = []

    for test in test_set:
        q = test['question']
        expected_kw = test['expected_keyword'].lower()

        # 1. Retrieval quality: does the right chunk appear in top-k?
        retrieved = vector_store.similarity_search(q, k=k)
        retrieved_text = ' '.join(r.page_content for r in retrieved).lower()
        retrieval_ok = expected_kw in retrieved_text
        retrieval_correct += int(retrieval_ok)

        # 2. Answer quality: does the final answer contain the expected keyword?
        t0 = time.time()
        answer = rag_chain.invoke(q)
        elapsed = time.time() - t0
        total_latency += elapsed

        answer_ok = expected_kw in answer.lower()
        answer_correct += int(answer_ok)

        results.append({
            'question': q,
            'answer': answer[:100],
            'retrieval_ok': retrieval_ok,
            'answer_ok': answer_ok,
            'latency': elapsed,
        })

        status = 'PASS' if (retrieval_ok and answer_ok) else 'FAIL'
        print(f'  [{status}] {q[:55]:55s} | ret={int(retrieval_ok)} ans={int(answer_ok)} | {elapsed:.2f}s')

    n = len(test_set)
    summary = {
        'retrieval_recall': retrieval_correct / n,
        'answer_accuracy': answer_correct / n,
        'avg_latency': total_latency / n,
        'results': results,
    }
    return summary


print('=== RAG EVALUATION ON GOLDEN TEST SET ===')
eval_summary = evaluate_rag(GOLDEN_TEST_SET, rag_chain, vector_store, k=cfg.retrieval_k)
print()
print(f'  Retrieval Recall@{cfg.retrieval_k}: {eval_summary["retrieval_recall"]:.1%}')
print(f'  Answer Accuracy      : {eval_summary["answer_accuracy"]:.1%}')
print(f'  Avg Latency          : {eval_summary["avg_latency"]:.2f}s')
print()
print('Target: Retrieval Recall > 80%, Answer Accuracy > 75% before production deploy.')

# ── LLM-as-Judge: Faithfulness Scoring ───────────────────────────────────────


# Faithfulness measures whether the answer only contains claims supported by
# the retrieved context — the key metric for preventing hallucination.
#
# This is 'LLM-as-judge' — use a strong LLM to evaluate a RAG answer.
# Used in RAGAS, DeepEval, and most production eval frameworks.
# The judge prompt is designed to force binary (yes/no) reasoning per claim.

def score_faithfulness(question: str, context: str, answer: str) -> dict:
    """Use LLM-as-judge to evaluate faithfulness of a RAG answer."""
    judge_prompt = (
        f'You are evaluating an AI answer for factual grounding.\n\n'
        f'Question: {question}\n\n'
        f'Context provided to the AI:\n{context}\n\n'
        f'AI Answer: {answer}\n\n'
        f'Evaluate:\n'
        f'1. Is every claim in the answer directly supported by the context? (yes/no)\n'
        f'2. Does the answer introduce any information NOT in the context? (yes/no)\n'
        f'3. Faithfulness score (0.0 = hallucinated, 1.0 = perfectly grounded): <score>\n'
        f'\nRespond in this exact format:\n'
        f'CLAIMS_SUPPORTED: yes|no\n'
        f'EXTRA_INFO: yes|no\n'
        f'FAITHFULNESS: <float 0.0-1.0>\n'
        f'EXPLANATION: <one sentence>'
    )
    verdict = llm.invoke(judge_prompt).content.strip()

    # Parse the structured response
    result = {'raw': verdict}
    for line in verdict.split('\n'):
        if 'FAITHFULNESS:' in line:
            try:
                result['faithfulness_score'] = float(line.split(':')[1].strip())
            except ValueError:
                result['faithfulness_score'] = None
        elif 'CLAIMS_SUPPORTED:' in line:
            result['claims_supported'] = 'yes' in line.lower()
        elif 'EXTRA_INFO:' in line:
            result['extra_info_added'] = 'yes' in line.lower()
    return result


# Run faithfulness eval on a sample query
test_q = 'What was the worldwide box office gross of IRobot?'
context_docs = vector_store.similarity_search(test_q, k=3)
context_str = format_docs(context_docs)
test_answer = rag_chain.invoke(test_q)

print(f'Evaluating faithfulness for: "{test_q}"')
print(f'Answer: {test_answer[:150]}')
print()
faith_result = score_faithfulness(test_q, context_str, test_answer)
print('Faithfulness verdict:')
for k, v in faith_result.items():
    if k != 'raw':
        print(f'  {k}: {v}')

