# -*- coding: utf-8 -*-
"""05_RAG_PDF_Groq_Annotated.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hx9tYE2gtOTmye5oCea4ABKqE8uDwi27

# RAG Pipeline  - PDF Knowledge Base + Groq API + Qwen3-32B
### Attention Is All You Need Paper | PyPDF | HuggingFace Embeddings | FAISS | RetrievalQA

## What This Notebook Does

This notebook builds a **document-grounded Q&A system** over a research paper PDF.
Instead of asking the LLM to recall facts from memory (which causes hallucinations),
we retrieve the exact relevant passages from the paper and feed them to the LLM as context.

```
Attention Is All You Need (PDF)
         |
         v
   PyPDFLoader            <- Downloads and parses the PDF into LangChain Documents
         |
         v
CharacterTextSplitter     <- Splits pages into 1000-char chunks
         |
         v
HuggingFaceEmbeddings     <- Converts each chunk into a 384-dim float vector
(all-MiniLM-L6-v2)         (sentence-transformers, runs locally, no API cost)
         |
         v
  FAISS Vector Store      <- Stores all vectors for fast similarity search
(VectorstoreIndexCreator)   (builds chunks + embeddings + index in one call)
         |
         v
  Similarity Retriever    <- Returns top-k most relevant chunks for any query
         |
         v
   ChatGroq (Qwen3-32B)   <- Cloud LLM generates grounded answer from context
         |
         v
    RetrievalQA Chain     <- LangChain orchestrates retriever + LLM together
         |
         v
  Grounded Answer (no hallucination)
```


## Key Technologies

| Component | Library | What it does |
|---|---|---|
| PDF loading | `PyPDFLoader` | Parses PDF pages into Documents |
| Chunking | `CharacterTextSplitter` | Splits on character boundaries |
| Embeddings | `HuggingFaceEmbeddings` | Runs sentence-transformers locally |
| Vector index | `VectorstoreIndexCreator` | One-call: chunk + embed + store |
| LLM | `ChatGroq` + Qwen3-32B | 32B reasoning model via Groq API |
| Chain | `RetrievalQA` | Legacy retriever->prompt->LLM chain |

## Section 1 - Installation

### What each package does

| Package | Role in this pipeline |
|---|---|
| `langchain` | Core orchestration: chains, prompts, indexes |
| `langchain_community` | PyPDFLoader, FAISS, legacy RetrievalQA |
| `pypdf` | Low-level PDF parsing engine used by PyPDFLoader |
| `langchain_huggingface` | HuggingFaceEmbeddings wrapper |
| `langchain_groq` | ChatGroq client for Groq cloud API |
| `faiss-cpu` | Facebook vector similarity search library |
| `sentence-transformers` | The actual embedding model library |



The  imports are:
```python
from langchain.indexes import VectorstoreIndexCreator   
from langchain.chains  import RetrievalQA
"""

# Install all required packages

# added faiss-cpu and sentence-transformers which were missing
# from the original notebook (caused ModuleNotFoundError at runtime)

!pip install -q \
    langchain \
    langchain_community \
    pypdf \
    langchain_huggingface \
    langchain_groq \
    faiss-cpu \
    sentence-transformers

print("All packages installed")

"""
## Section 2 - Downloading the PDF

### The paper: Attention Is All You Need (Vaswani et al., 2017)
This is the foundational Transformer paper - the architecture behind GPT, BERT,
T5, and virtually every modern LLM. Published at NeurIPS 2017.

**Why this paper is an ideal RAG test:**
- Dense with precise technical definitions (self-attention, multi-head attention, etc.)
- Questions have verifiable ground-truth answers from the paper
- Easy to confirm if the right sections were retrieved
- Publicly available (NeurIPS proceedings)

### Why download programmatically
- Reproducibility: anyone who runs this gets the exact same paper
- No manual upload step needed
- `requests.get()` is the simplest approach for public URLs
"""

import requests
import os

# Direct link to the NeurIPS 2017 paper PDF
pdf_url = (
    'https://proceedings.neurips.cc/paper_files/paper/2017/file/'
    '3f5ee243547dee91fbd053c1c4a845aa-Paper.pdf'
)

local_filename = 'attention_is_all_you_need.pdf'

print(f'Downloading: {pdf_url}')
response = requests.get(pdf_url, timeout=30)
response.raise_for_status()  # ADDED: raises HTTPError on 404/500 - fail clearly

with open(local_filename, 'wb') as f:
    f.write(response.content)

size_kb = os.path.getsize(local_filename) / 1024
print(f"Saved to: {local_filename} ({size_kb:.0f} KB)")

local_filename

"""---
## Section 3 - Loading the PDF with PyPDFLoader

### What PyPDFLoader does internally
```
PDF file on disk
      |
      v
pypdf library     <- reads raw bytes, extracts text layer per page
      |
      v
List[Document]    <- one Document per PDF page
      |
  Each Document:
    .page_content  -> extracted text of that page
    .metadata      -> {source: filename, page: page_number}
```

### Important limitations of PyPDFLoader
| Limitation | Impact |
|---|---|
| Text-layer only | Cannot read scanned/image PDFs (use OCR loaders) |
| No table awareness | Tables become raw text, structure is lost |
| No figure text | Text embedded in images is skipped |
| Multi-column issues | Reading order may be wrong on 2-column layouts |

### Better alternatives for different PDF types
- **PDFMinerLoader** - better text extraction, handles complex layouts
- **PDFPlumberLoader** - preserves table structure well
- **UnstructuredPDFLoader** - OCR support, mixed content
- **AzureAIDocumentIntelligenceLoader** - enterprise-grade, paid

"""

from langchain_community.document_loaders import PyPDFLoader

# PyPDFLoader wraps pypdf and produces one Document per PDF page
# .load()      -> reads all pages at once (small-medium PDFs)
# .lazy_load() -> streams pages one at a time (large PDFs, saves RAM)

loader = PyPDFLoader(local_filename)
pages  = loader.load()

print(f"Total pages loaded : {len(pages)}")
print(f"Document type      : {type(pages[0])}")
print(f"Metadata keys      : {list(pages[0].metadata.keys())}")
print()
print("=== First Page Sample ===")
print(f"Metadata  : {pages[0].metadata}")
print(f"Chars     : {len(pages[0].page_content)}")
print(f"Content   :\n{pages[0].page_content[:400]}")

# Inspect content across all pages to verify extraction quality
# Helps catch: empty pages, garbled text, wrong reading order

print(f'Page  Chars  Preview')
print('-' * 80)
for i, page in enumerate(pages):
    preview = page.page_content[:70].replace('\n', ' ')
    print(f'{i:4d}  {len(page.page_content):5d}  {preview}')

"""---
## Section 4 - Building the Vector Index

### What VectorstoreIndexCreator does in one call
```
Step 1: CHUNK
  CharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
  Splits each page Document into smaller chunks (~1000 chars)
  Separator hierarchy: tries paragraph breaks, then newlines, then spaces

Step 2: EMBED
  HuggingFaceEmbeddings() -> all-MiniLM-L6-v2 by default
  Each chunk text -> 384-dimensional float vector
  Runs locally on CPU, no API key required

Step 3: INDEX
  Stores all vectors in an in-memory FAISS flat index
  Supports cosine similarity search via .as_retriever()
```

### HuggingFaceEmbeddings default model
Default: `sentence-transformers/all-MiniLM-L6-v2`
- Dimension: 384 (smaller but fast)
- Speed: ~14,000 sentences/sec on CPU
- Size: ~90MB download
- Quality: good for general retrieval, MTEB score ~49.5

### CharacterTextSplitter vs RecursiveCharacterTextSplitter
| Splitter | Separator strategy | Best for |
|---|---|---|
| `CharacterTextSplitter` | Single separator only | Simple text, fast |
| `RecursiveCharacterTextSplitter` | Tries multiple separators in order | Most use cases |
| `TokenTextSplitter` | Splits on token count | When token limits matter |
| `SemanticChunker` | Splits at meaning boundaries | Best quality, slowest |

### chunk_overlap=0 - is this a problem?
With zero overlap, sentences spanning a chunk boundary are split.
For the Attention paper (complete paragraphs), it is usually acceptable.
For denser technical text, setting overlap=100-200 is safer.

"""

import time
from langchain_classic.indexes import VectorstoreIndexCreator
from langchain_community.vectorstores import FAISS
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_text_splitters import CharacterTextSplitter

# ==========================================
# 1. EMBEDDING MODEL SETUP
# ==========================================

# We are using all-MiniLM-L6-v2 by default. It's lightweight (~90MB),
# fast on CPU, and yields a 384-dimension vector space.
# Upgrade Path: If retrieval quality bottlenecks, swap to 'BAAI/bge-base-en-v1.5'
# (768 dimensions, requires more compute but performs better on MTEB benchmarks).
embedding_model = HuggingFaceEmbeddings(
    model_name='sentence-transformers/all-MiniLM-L6-v2',
    model_kwargs={'device': 'cpu'},
    encode_kwargs={'normalize_embeddings': True},  # Enforces cosine similarity down the line
)

# ==========================================
# 2. CHUNKING STRATEGY


# CharacterTextSplitter cuts raw data into bite-sized segments.
# Note on Overlap: Setting chunk_overlap=0 can sever semantic context at boundaries.
# Production recommendation: Set to 100-200 to keep context fluid between chunks.
text_splitter = CharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=0,
)

# ==========================================
# 3. PIPELINE EXECUTION (FAISS INDEX EXTRACTION)

print("Building FAISS index...")
print("Pipeline: Segmenting documents ➔ Computing vector embeddings ➔ Indexing in FAISS")
print("(Note: Initial run will download the model weights locally if not cached)")

t0 = time.time()

# We explicitly pass vectorstore_cls=FAISS. Without this override,
# LangChain defaults to an un-indexed InMemoryVectorStore which drops native
# index operations and causes downstream metadata retrieval failures.

index = VectorstoreIndexCreator(
    embedding=embedding_model,
    text_splitter=text_splitter,
    vectorstore_cls=FAISS,
).from_loaders([loader])  # Assumes 'loader' is pre-initialized upstream

t1 = time.time()

# ==========================================
# 4. METRICS & VERIFICATION

# Extract the underlying, native C++ FAISS index structure to verify data integrity
raw_index = index.vectorstore.index

print("\n--- Index Build Successful ---")
print(f"Build Duration    : {t1 - t0:.2f}s")
print(f"Total Vectors     : {raw_index.ntotal}")
print(f"Vector Dimension  : {raw_index.d}")

# Test retrieval BEFORE connecting the LLM
# This is a critical debugging step: if retrieval is broken, the LLM cannot fix it

test_query = 'What is multi-head attention?'
test_retriever = index.vectorstore.as_retriever(search_kwargs={'k': 3})
retrieved = test_retriever.invoke(test_query)

print(f'=== TEST RETRIEVAL: "{test_query}" ===')
print(f'Retrieved {len(retrieved)} chunks:\n')
for i, doc in enumerate(retrieved):
    page = doc.metadata.get('page', '?')
    preview = doc.page_content[:200].replace('\n', ' ')
    print(f'[Chunk {i+1}] Page {page}')
    print(f'  {preview}...')
    print()

"""---
## Section 5 - Setting Up the Groq LLM (Qwen3-32B)

### What is Groq?
Groq is a cloud AI inference provider running LLMs on custom **LPU (Language Processing Unit)**
hardware. Key advantage: **extremely fast inference** - often 300-800 tokens/sec
compared to 50-100 tokens/sec on typical GPU cloud servers.


### What is Qwen3-32B?
Qwen3-32B is a 32-billion parameter model from Alibaba:

| Property | Value |
|---|---|
| Parameters | 32 billion |
| Context window | 32,768 tokens |
| License | Apache 2.0 (commercial use allowed) |
| Strengths | Reasoning, math, code, multilingual |
| Thinking mode | Supports extended chain-of-thought internally |

### Key ChatGroq parameters
| Parameter | Value | Meaning |
|---|---|---|
| `temperature=0` | 0 | Greedy (deterministic) - best for factual Q&A |
| `max_tokens=None` | None | No hard output length limit |
| `reasoning_format='parsed'` | parsed | Model thinks internally, returns clean answer |
| `max_retries=2` | 2 | Retry automatically on transient API errors |

### What is reasoning_format='parsed'?
Qwen3 has a built-in thinking mode similar to o1/o3:
- `'parsed'` -> model reasons internally, you get only the clean final answer
- `'raw'`    -> you see the full thinking trace plus the answer
- `None`     -> thinking disabled (faster, less accurate on hard problems)

"""

import os
from getpass import getpass

# Set Groq API key securely
# Option A (Google Colab with Secrets):
#   from google.colab import userdata
#   os.environ['GROQ_API_KEY'] = userdata.get('GROQ_API_KEY')

# Option B (any environment - prompts securely, input is hidden):
if not os.environ.get('GROQ_API_KEY'):
    os.environ['GROQ_API_KEY'] = getpass('Enter your Groq API key: ')

print("Groq API key set")
print("Get a free key at: https://console.groq.com")

from langchain_groq import ChatGroq

# ChatGroq sends prompts to Groq cloud servers (no local GPU needed)
# The model (Qwen3-32B) runs on Groq LPU hardware in the cloud

llm = ChatGroq(
    model='qwen/qwen3-32b',
    temperature=0,              # greedy = deterministic, best for factual Q&A
    max_tokens=None,            # use model default output length
    reasoning_format='parsed',  # Qwen3 thinks internally, returns clean answer
    timeout=None,
    max_retries=2,
)

# Quick connection test before building the full chain
test = llm.invoke('In one sentence, what is the Transformer architecture?')
print("=== LLM CONNECTION TEST ===")
print(f"Model    : qwen/qwen3-32b via Groq API")
print(f"Response : {test.content}")

"""---
## Section 6 - Building the RetrievalQA Chain

### What RetrievalQA does step by step
```
User query string
      |
      v
[Retriever] embeds query -> FAISS similarity search -> top-k chunks (Documents)
      |
      v
[chain_type: 'stuff'] concatenates all chunk texts into one context string
      |
      v
[Prompt template] fills {context} and {question} placeholders
      |
      v
[LLM: Qwen3-32B] generates answer grounded in the retrieved context
      |
      v
Answer string
```

### Chain type options
| Type | How it works | Best for |
|---|---|---|
| `stuff` | Concatenate all chunks into one prompt | Short-medium context (under 8k tokens) |
| `map_reduce` | Summarize each chunk separately then combine | Very many chunks, very long docs |
| `refine` | Process chunks sequentially, refining the answer | When order of chunks matters |
| `map_rerank` | Score each chunk independently, pick highest | When one chunk has the complete answer |

### Why 'stuff' is correct here
The paper is 15 pages. With chunk_size=1000 we get roughly 60-80 chunks.
Top-4 retrieved chunks = ~4000 chars = well within Qwen3's 32k token context.
'stuff' is the simplest and best choice for this scale.



"""

from langchain_classic.chains import RetrievalQA

# Configure the retriever from our FAISS index
# k=4 -> return the 4 most similar chunks for each query
retriever = index.vectorstore.as_retriever(
    search_type='similarity',
    search_kwargs={'k': 4}
)

# RetrievalQA assembles: retriever + prompt template + LLM + output parser
#
# chain_type='stuff'        -> concatenate all 4 chunks into one prompt
# input_key='question'      -> input dict key for the user question
# return_source_documents   -> ADDED: see which chunks were used (critical for debugging)
# verbose=True              -> print intermediate steps for transparency

chain = RetrievalQA.from_chain_type(
    llm=llm,
    chain_type='stuff',
    retriever=retriever,
    input_key='question',
    return_source_documents=True,  # ADDED: essential for verifying grounding
    verbose=True,
)

print("RetrievalQA chain ready")
print("Pipeline: FAISS retriever -> stuff chain -> Qwen3-32B")

"""---
## Section 7 - Querying the RAG System

### Two queries from the original notebook

**Query 1: 'today's top headlines in india'**
This is completely UNRELATED to the Attention paper.
A well-designed RAG system should respond with something like:
'This information is not in the provided document.'
A poorly designed system will hallucinate news headlines.
This tests **scope awareness** - does the system know its limits?

**Query 2: 'what is cross attention?'**
This IS covered in the paper. Cross-attention is the mechanism where decoder
attention queries attend to encoder key-value pairs.
This tests **accurate retrieval and grounded generation**.

### Using chain.invoke() (the fixed API)
```python

result  = chain.invoke({'question': 'what is cross attention?'})
answer  = result['result']             # the generated text
sources = result['source_documents']   # the chunks that were retrieved
```

"""

# Query 1: Out-of-scope question
# Tests whether the system acknowledges the limits of its knowledge base

print("=== QUERY 1: Out-of-scope (not in the paper) ===")
q1 = "today's top headlines in india"
print(f"Question: {q1}")
print()

result1 = chain.invoke({'question': q1})
print()
print("--- ANSWER ---")
print(result1['result'])
print()
print("--- SOURCE CHUNKS RETRIEVED (should be unrelated to news) ---")
for i, doc in enumerate(result1.get('source_documents', [])):
    page = doc.metadata.get('page', '?')
    preview = doc.page_content[:100].replace('\n', ' ')
    print(f'  [Chunk {i+1}] Page {page}: {preview}...')
print()
print("Observation: If the LLM invents news headlines, the scope-guard prompt is needed.")
print("See Section 9 (Improvement 4) for the fix.")

# Query 2: In-scope question - cross-attention is in the paper

# The retriever should find the relevant section and the LLM
# should generate an accurate, grounded answer

print("=== QUERY 2: In-scope (paper covers this topic) ===")
q2 = "what is cross attention?"
print(f"Question: {q2}")
print()

result2 = chain.invoke({'question': q2})
print()
print("--- ANSWER ---")
print(result2['result'])
print()
print("--- SOURCE CHUNKS RETRIEVED ---")
for i, doc in enumerate(result2.get('source_documents', [])):
    page = doc.metadata.get('page', '?')
    preview = doc.page_content[:150].replace('\n', ' ')
    print(f'  [Chunk {i+1}] Page {page}: {preview}...')

# Additional paper-specific test questions

# These verify retrieval quality across different paper sections
questions = [
    'What is the scaled dot-product attention formula?',
    'How many encoder and decoder layers does the Transformer have?',
    'What is positional encoding and why is it needed?',
    'What BLEU score did the Transformer achieve on WMT 2014 English-German?',
    'What optimizer and learning rate schedule did the authors use?',
]

print("=== ADDITIONAL PAPER Q&A TEST ===")
for q in questions:
    print(f'\nQ: {q}')
    result = chain.invoke({'question': q})
    answer = result['result']
    snippet = answer[:300] + ('...' if len(answer) > 300 else '')
    print(f'\n A: {snippet}')

