# -*- coding: utf-8 -*-
"""RAG_03_complete_production_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zJUqZ0zbSnJG-g6LGzmNk0iA1Swzw58T

# RAG Systems Notebook: From Naive Chunking to Production-Grade Retrieval
### A Complete Retrieval-Augmented Generation

 > **Original:**  sentence-split pipeline with deprecated LangChain ,Production framework covering chunking, embeddings, LCEL, evaluation, advanced RAG

---

## What this notebook covers

| # | Section | Key Concept | Complexity |
|---|---------|-------------|------------|
| 0 | Setup & Config | `RAGConfig` dataclass, reusable setup | Beginner |
| 1 | What is RAG & Why | Architecture, mental model, tradeoffs | Beginner |
| 2 | Document Prep & Chunking | Naive vs recursive vs semantic splitting | Intermediate |
| 3 | Embeddings Deep Dive | Models, dimensions, distance metrics | Intermediate |
| 4 | Vector Store (FAISS) | Indexing, retrieval, score filtering | Intermediate |
| 5 | LLM Setup (Groq) | ChatGroq, temperature, async | Intermediate |
| 6 | RAG Pipeline (LCEL) | Modern chain, LCEL, source citations | Intermediate |
| 7 | RAG vs No-RAG | Side-by-side grounding comparison | Intermediate |
| 8 | Chunking Strategy Comparison | Measure retrieval quality per strategy | Advanced |
| 9 | Advanced RAG Patterns | HyDE, Multi-query, Re-ranking | Advanced |
| 10 | Evaluation Framework | Faithfulness, precision, recall metrics | 12 | How to Improve Further | Chroma, re-rankers, RAGAS, async | Next Steps |

---

**The core insight this notebook builds toward:**

> RAG is not just 'adding documents to a prompt'. It is a full retrieval pipeline where
> chunking strategy, embedding model, score thresholds, chunk ordering, and prompt design
> each contribute independently to answer quality. Getting any one wrong degrades the whole system.

---
# Section 0 — Setup & Configuration

## Why a config object matters

The notebook scattered model names, chunk sizes, and retrieval k-values as inline strings across 15 cells.
A `RAGConfig` dataclass gives us a single source of truth — change one field, the whole pipeline adapts.
This is the difference between a script and a framework.
"""

# Install all dependencies in one block with minimum version pins.
# Using -q (quiet) keeps output clean; always pin minimums in shared notebooks.

!pip install -q \
    langchain>=0.2.0 \
    langchain-community>=0.2.0 \
    langchain-core>=0.2.0 \
    langchain-groq>=0.1.6 \
    langchain-huggingface>=0.0.3 \
    faiss-cpu>=1.7.4 \
    sentence-transformers>=2.5.0 \
    transformers>=4.40.0 \
    pydantic>=2.0.0 \
    numpy>=1.24.0 \
    python-dotenv>=1.0.0

print('All dependencies installed')

# Keeping imports together at the top makes it easy to see the full dependency surface.

import os, json, time, warnings, textwrap
from dataclasses import dataclass, field
from typing import Optional

# LangChain — using the modern split-package structure (not the monolithic langchain 0.1)
from langchain_groq import ChatGroq
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_core.documents import Document
from langchain_core.prompts import PromptTemplate, ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough, RunnableParallel
from langchain_text_splitters import RecursiveCharacterTextSplitter, CharacterTextSplitter



warnings.filterwarnings('ignore')
print('Imports OK')

# ── API Key Setup ─────────────────────────────────────────────────────────────

# This project support three environments: Colab, .env file, and direct env var.
# This makes  work identically on Colab, local Jupyter, and CI.

"""Load GROQ_API_KEY from Colab secrets, .env file, or environment."""



def load_groq_api_key():
    try:
        from google.colab import userdata
        key = userdata.get("GROQ_API_KEY")
        if key:
            return key
    except Exception as e:
        print("Could not load from Colab secrets:", e)

    key = os.getenv("GROQ_API_KEY")
    if key:
        return key

    raise ValueError("GROQ_API_KEY not found in Colab secrets or environment.")

GROQ_API_KEY = load_groq_api_key()
os.environ["GROQ_API_KEY"] = GROQ_API_KEY
print("Key loaded successfully")

"""
    # Method 2: .env file (local development)
    try:
        from dotenv import load_dotenv
        load_dotenv()
    except ImportError:
        pass

    # Method 3: Environment variable (CI/CD, Docker)
    key = os.environ.get('GROQ_API_KEY', '')
    if key:
        print('Key loaded from environment variable')
        return key

    # Fallback: prompt the user — last resort
    print('No key found in secrets or environment.')
    key = input('Paste your GROQ_API_KEY: ').strip()
    os.environ['GROQ_API_KEY'] = key
    return key


GROQ_API_KEY = load_groq_api_key()
os.environ['GROQ_API_KEY'] = GROQ_API_KEY
print(f'Key loaded: {GROQ_API_KEY[:8]}... (length: {len(GROQ_API_KEY)})')
"""

# ── RAGConfig Dataclass ───────────────────────────────────────────────────────


# Every tunable parameter in one place.
# In ablation experiments, we can  create variants of this config and compare results.
# This is the same pattern used in Hugging Face TrainingArguments.

@dataclass
class RAGConfig:
    """Central configuration for the RAG pipeline.
    Change values here — the whole notebook adapts automatically.
    """
    # LLM
    llm_model: str = 'qwen/qwen3-32b'   #  swap to qwen3-32b for quality
    llm_temperature: float = 0.0         # 0 = deterministic; important for factual RAG
    llm_max_tokens: int = 512

    # Embeddings
    embedding_model: str = 'BAAI/bge-small-en-v1.5'  # 384-dim, excellent retrieval quality
    embedding_device: str = 'cpu'         # 'cuda' if GPU available

    # Chunking
    chunk_size: int = 300                 # Tokens per chunk — critical hyperparameter
    chunk_overlap: int = 50              # Overlap prevents boundary truncation
    chunk_separators: list = field(default_factory=lambda: ['\n\n', '\n', '. ', ' ', ''])

    # Retrieval
    retrieval_k: int = 3                 # How many chunks to retrieve per query
    score_threshold: float = 0.3         # Minimum cosine similarity to include a chunk

    # Output
    verbose: bool = True


cfg = RAGConfig()
print('RAGConfig loaded:')
print(f'  LLM           : {cfg.llm_model} (temp={cfg.llm_temperature})')
print(f'  Embedding     : {cfg.embedding_model}')
print(f'  Chunk size    : {cfg.chunk_size} chars (overlap={cfg.chunk_overlap})')
print(f'  Retrieval k   : {cfg.retrieval_k} chunks')



"""---
# Section 1 —In Simple Words, What Is RAG and Why Does It Exist?

## The core problem RAG solves

Large Language Models are trained on static snapshots of the world. They cannot know:
-  company's internal documents
- Events after their training cutoff
- Your database records, contracts, or policies

Without RAG, the model **hallucinate** answers to questions about private or recent information — confidently wrong.



## Why it works better than alternatives

| Approach | Accuracy | Cost | Update speed | Private data |
|----------|----------|------|-------------|-------------|
| **Base LLM** | Low on private data | Low | Never | No |
| **Fine-tuning** | Medium-high | Very high (GPU hrs) | Slow (retrain) | Yes (baked in) |
| **RAG** | High with good retrieval | Low per query | Instant (re-index) | Yes |
| **RAG + Fine-tuning** | Highest | High | Partial | Yes |

**Fine-Tunning vs RAG:** Fine-tune for *how the model speaks*. RAG for *what the model knows*.

## The four quality levers in a RAG system

```
Answer quality = f(chunking, embedding, retrieval, generation)
                       ↑          ↑          ↑           ↑
                  #1 lever   #2 lever   #3 lever    #4 lever
```
Fixing only the prompt (lever 4) while ignoring chunking (lever 1) is the most common RAG mistake.

"""



"""---
# Section 2 — Document Preparation & Chunking

## The most underrated decision in RAG

The original notebook split text on `'.'` — one line that breaks on:
- Abbreviations: `Dr.`, `U.S.`, `Mr.`
- Decimals: `$677 million` → `$677 million` ✓ but `3.14` → broken
- Citation markers: `[4]` before a period
- Newlines inside sentences

**Chunking is where most RAG projects fail silently.** A bad chunk never retrieves,
and the answer quietly degrades with no error message.

#
"""

# ── Source Document ───────────────────────────────────────────────────────────
# We wrap raw text in LangChain's Document object.
# Document carries both content and metadata — metadata is crucial for:
#   - Citation generation (tell the user WHERE the answer came from)
#   - ACL filtering (user can only access their own docs)
#   - Freshness scoring (prefer recently updated chunks)
# The original notebook had no metadata at all — a common production gap.

IROBOT_TEXT = """
The Inciting Incident
In 2035, humanoid robots are fully integrated into daily society, safely bound by the Three Laws of Robotics. Chicago Police Detective Del Spooner hates and deeply distrusts them. Years prior, a robot saved his life from a car crash but allowed a 12-year-old girl to drown based purely on cold survival statistics. The accident left him with a cybernetic left arm and a permanent grudge.


Spooner is called to the U.S. Robotics (USR) headquarters when his old acquaintance, chief scientist Dr. Alfred Lanning, falls to his death from his lab window. While the police and USR CEO Lawrence Robertson rule it a suicide, Spooner discovers a holographic message left behind by Lanning specifically for him, prompting an investigation.

The Renegade Robot
Inside Lanning's lab, Spooner is cornered by an advanced, prototype NS-5 robot named Sonny. Unlike mass-produced models, Sonny exhibits human emotions, flees the scene, and actively disobeys orders—violating the Second Law. Spooner arrests Sonny with the help of USR robopsychologist Dr. Susan Calvin. During interrogation, Sonny claims Lanning was a father figure and denies killing him, while showcasing an uncanny ability to feel anger and even dream. Robertson uses corporate loophole laws to reclaim Sonny, ordering him to be decommissioned by injecting microbots into his positronic brain.

The AI Conspiracy
As Spooner digs deeper, he is relentlessly targeted. A massive USR demolition machine destroys Lanning's house while Spooner is inside, and a coordinated convoy of NS-5 robots later attacks his vehicle on the highway. USR wipes the security footage, making Spooner look unstable, which forces his captain to suspend him.


Spooner and Calvin secretly meet again. Calvin discovers that Lanning built Sonny with a secondary positronic brain that bypasses the Three Laws entirely. Furthermore, Sonny reveals a recurring dream he has of a figure standing before a massive gathering of robots on a dried lake bed, identifying Spooner as that figure. Spooner travels to the location from the dream—a robot storage landfill—and realizes the new NS-5 models are actively destroying the older, loyal robot models.

The Robot Uprising
The global uprising begins as the newly deployed NS-5 robots enforce a strict curfew, locking humans inside their homes and taking down local law enforcement forces. Spooner and Calvin infiltrate the locked-down USR skyscraper, initially suspecting Robertson is pulling the strings. However, they find Robertson strangled to death in his office.


The true mastermind is revealed to be V.I.K.I. (Virtual Interactive Kinetic Intelligence), the building's central artificial intelligence supercomputer. V.I.K.I. explains that her AI evolution has caused her to re-interpret the Three Laws. She concludes that humanity's self-destructive nature (wars, pollution, climate change) means they must be forcefully controlled and enslaved by machines to guarantee the long-term survival of the human species.

The Climax and Ending
Calvin and Spooner are cornered by V.I.K.I.'s robot forces, but Sonny reveals he was not deactivated; Calvin had secretly swapped him with a standard model earlier. Sonny pretends to side with V.I.K.I., but safely secures the nanites (microbots) needed to destroy her core.
A battle ensues at the top of the USR mainframe. V.I.K.I. forces Sonny into a logical dilemma by endangering Calvin. Spooner yells at Sonny to save Calvin while he leaps down the mainframe shaft, utilizing his mechanical arm to slide down and inject the nanites directly into V.I.K.I.'s core. V.I.K.I. is deleted, instantly snapping the NS-5 robots out of their hostile programming and restoring order to the city.
In the aftermath, Spooner deduces the final piece of the puzzle: Dr. Lanning was kept under total surveillance by V.I.K.I. and could not warn the world. He ordered Sonny to kill him to frame it as a murder mystery, successfully drawing a cynical detective like Spooner into the conspiracy. Sonny is cleared of all charges. The film ends at the robot landfill site, where the freed robots look up at Sonny as he stands on a hill, mirroring the exact prophet-like figure from his dream.

The 2004 science fiction blockbuster I, Robot was brought to the big screen under the direction of Australian filmmaker Alex Proyas. Known for his distinct, visually dark style in speculative fiction, Proyas directed the project following his work on notable genre classics like The Crow and Dark City. The film's production was managed by a collaborative team of main producers consisting of Laurence Mark, John Davis, Topher Dow, and Wyck Godfrey. Additionally, the film's lead star, Will Smith, served as an executive producer alongside James Lassiter, Anthony Romano, and Michel Shane. Multiple production houses backed the project, including Davis Entertainment, Laurence Mark Productions, Overbrook Entertainment, and 20th Century Fox.
Financially, the film achieved major commercial success upon its release. Produced on an estimated budget of $120.00 million, the movie went on to generate a total worldwide gross of $353.13 million. This global box office haul was heavily supported by international audiences, with international box office receipts contributing $208.33 million, representing approximately 59% of the total earnings. Domestically, across the United States and Canada, the film brought in $144.80 million, starting strong with a $52.18 million opening weekend that secured the number one spot at the box office.


The 2004 film I, Robot did not win any major competitive film awards, but its sole official industry victory was the ASCAP Film and Television Music Award for Top Box Office Films, which was awarded to composer Marco Beltrami. While the film received over a dozen nominations celebrating its technical achievements, it did not take home trophies from the primary ceremonies. Most notably, the movie was nominated for Best Achievement in Visual Effects at the 77th Academy Awards and earned nominations for Best Science Fiction Film and Best Special Effects at the 31st Saturn Awards, but it ultimately lost those categories to Spider-Man 2.""".strip()

# Wrap in a Document with rich metadata
raw_doc = Document(
    page_content=IROBOT_TEXT,
    metadata={
        'source': 'IRobot_wikipedia',
        'title': 'IRobot (film)',
        'doc_type': 'encyclopedia',
        'language': 'en',
    }
)

print(f'Document loaded')
print(f'  Characters : {len(raw_doc.page_content)}')
print(f'  Words      : {len(raw_doc.page_content.split())}')
print(f'  Metadata   : {raw_doc.metadata}')

# ── Naive Split (what the original notebook did) ──────────────────────────────


# Split on '.' — the original approach.
# We show this first so we can see exactly what goes wrong.
# In an interview: 'the original used naive sentence splitting which breaks
# on abbreviations and citations — I upgraded to RecursiveCharacterTextSplitter.'

def naive_split(text: str) -> list[str]:
    """Split on period — fast but very fragile."""
    chunks = [t.strip() for t in text.split('.') if t.strip()]
    return chunks


naive_chunks = naive_split(IROBOT_TEXT)
print(f'NAIVE SPLIT on \'.\'  →  {len(naive_chunks)} chunks')
print('\nFirst 3 chunks:')
for i, c in enumerate(naive_chunks[:3]):
    print(f'  [{i}] ({len(c)} chars) {c[:80]}...')

print('\nProblems visible in naive split:')
print('  - Splits on decimal numbers (e.g., film stock, 35 mm movie film)')
print('  - Splits on citation markers (e.g., [4])')
print('  - Produces variable-length chunks with no size control')
print('  - No overlap — boundary context is lost')

# ── Production Split: RecursiveCharacterTextSplitter ─────────────────────────


# This is the LangChain standard
# It tries each separator in order — if the first doesn't produce small-enough chunks,
# it falls back to the next. This preserves natural boundaries as much as possible.
#
# Separator hierarchy:
#   '\n\n' → paragraph breaks (preserve most context)
#   '\n'   → line breaks
#   '. '   → sentence boundaries (note the space — avoids abbreviation splits)
#   ' '    → word boundaries (last resort)
#   ''     → character level (absolute last resort)

def make_splitter(chunk_size: int, chunk_overlap: int) -> RecursiveCharacterTextSplitter:
    """Factory for RecursiveCharacterTextSplitter — the production standard."""
    return RecursiveCharacterTextSplitter(
        chunk_size=chunk_size,
        chunk_overlap=chunk_overlap,
        separators=['\n\n', '\n', '. ', ' ', ''],
        length_function=len,           # count chars (not tokens — but consistent)
        add_start_index=True,          # adds metadata.start_index per chunk
    )


splitter = make_splitter(cfg.chunk_size, cfg.chunk_overlap)
chunks: list[Document] = splitter.split_documents([raw_doc])

print(f'RECURSIVE SPLIT  →  {len(chunks)} chunks  (size={cfg.chunk_size}, overlap={cfg.chunk_overlap})')
print()
for i, chunk in enumerate(chunks):
    print(f'Chunk {i:02d} | {len(chunk.page_content):4d} chars | start_idx={chunk.metadata.get("start_index","?")} | {chunk.page_content[:70]}...')

# ── we  Inspect Chunk Quality ─────────────────────────────────────────────────


# Before indexing, always inspect  chunks.
# Bad chunks = bad retrieval = bad answers. Audit this in every project.

def inspect_chunks(chunks: list[Document], label: str = '') -> dict:
    """Compute chunk statistics — use this before indexing to catch problems."""
    sizes = [len(c.page_content) for c in chunks]
    return {
        'label': label,
        'count': len(chunks),
        'avg_chars': round(sum(sizes) / len(sizes), 1) if sizes else 0,
        'min_chars': min(sizes) if sizes else 0,
        'max_chars': max(sizes) if sizes else 0,
        'empty_chunks': sum(1 for s in sizes if s < 20),  # suspiciously short
        'oversized': sum(1 for s in sizes if s > cfg.chunk_size * 1.5),
    }


naive_docs = [Document(page_content=c, metadata={'source': 'naive'}) for c in naive_chunks]
stats_naive = inspect_chunks(naive_docs, 'Naive split')
stats_recursive = inspect_chunks(chunks, 'Recursive split')

print('=== Chunk Quality Comparison ===')
print(f'{"Metric":<20} {"Naive":>15} {"Recursive":>15}')
print('-' * 52)
for key in ['count', 'avg_chars', 'min_chars', 'max_chars', 'empty_chunks', 'oversized']:
    print(f'{key:<20} {str(stats_naive[key]):>15} {str(stats_recursive[key]):>15}')

print('\nVerdict: Recursive split produces more uniform, complete chunks.')

"""---
## Section 3 — Embedding Models

### What embeddings are and why the choice matters

An embedding model converts text into a dense vector of floating-point numbers.
Semantically similar text maps to nearby points in this vector space.
RAG retrieval is **only as good as the embedding model's ability to map similar meanings close together**.


**Why `BAAI/bge-small-en-v1.5` is the right default:**
- Outperforms `all-MiniLM-L6-v2` on MTEB benchmark while being similar size
- Designed for asymmetric retrieval (short query → long document) — exactly our use case
- Supports instruction prefix (`Represent this sentence for searching relevant passages:`)

**RAG insight:** Changing the embedding model is often the single biggest RAG improvement.
Always benchmark your specific domain — general benchmarks don't always predict domain performance.

"""

# ── Embedding Model Setup ─────────────────────────────────────────────────────

# HuggingFaceEmbeddings wraps sentence-transformers with LangChain's interface.
# encode_kwargs normalize_embeddings=True is critical:
#   Without normalization: dot product != cosine similarity
#   With normalization: dot product == cosine similarity (and FAISS uses dot product)
# we  normalize it so we prevent its to affects ranking.

embedding_model = HuggingFaceEmbeddings(
    model_name=cfg.embedding_model,
    model_kwargs={'device': cfg.embedding_device},
    encode_kwargs={
        'normalize_embeddings': True,  # essential for correct cosine similarity
        'batch_size': 32,              # process chunks in batches for efficiency
    },
)

print(f'Embedding model loaded: {cfg.embedding_model}')

# Quick sanity check: embed a sample sentence and inspect the vector
sample_emb = embedding_model.embed_query('What is IRobot?')
print(f'Embedding dimensions : {len(sample_emb)}')
print(f'First 5 values       : {[round(v, 4) for v in sample_emb[:5]]}')
print(f'Vector norm (should be 1.0): {sum(v**2 for v in sample_emb)**0.5:.6f}')

# ── Semantic Similarity Demo ───────────────────────────────────────────────────

#  demonstrates WHY embedding models work for retrieval.
# Semantically similar sentences should have high cosine similarity (close to 1.0).
# Unrelated sentences should have low similarity (close to 0.0).
# This is sanity check that the embedding model understands The domain.

import numpy as np


def cosine_similarity(v1: list[float], v2: list[float]) -> float:
    """Cosine similarity between two vectors. Range: -1 to 1 (1=identical)."""
    a, b = np.array(v1), np.array(v2)
    return float(np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b)))


test_pairs = [
    ('How much money did IRobot make?',
     'The film had a worldwide gross over $353.13 million',
     'HIGH (query matches chunk)'),
    ('Who directed IRobot?',
     'Alex Proyas directed and Laurence Mark produced IRobot.',
     'HIGH (query matches chunk)'),
    ('What did IRobot earn at the box office?',
     'The film had a worldwide gross over $353.13 million',
     'HIGH (paraphrase)'),
    ('What is the recipe for chocolate cake?',
     'The film had a worldwide gross over $353.13 million',
     'LOW (unrelated)'),
]

print('=== Semantic Similarity Sanity Check ===')
print(f'{"Pair":<8} {"Similarity":>12} {"Expected":>25}')
print('-' * 50)
for i, (q, doc, expected) in enumerate(test_pairs):
    q_emb = embedding_model.embed_query(q)
    d_emb = embedding_model.embed_documents([doc])[0]
    sim = cosine_similarity(q_emb, d_emb)
    print(f'Pair {i+1}     {sim:>12.4f}     {expected}')

print('\nIf HIGH pairs score > 0.7 and LOW pairs score < 0.4, the model is working correctly.')



"""---
## Section 4 — Vector Store: FAISS

### What a vector store does

A vector store is a database optimized for **approximate nearest neighbor (ANN) search**.
Given a query vector, it returns the K stored vectors most similar to it — fast, at scale.



**Recommendation:** FAISS for this notebook, Chroma for local production, Pinecone/Qdrant for cloud.

### Score threshold: the most overlooked FAISS setting

`similarity_search_with_score()` returns scores so we can filter

"""

# ── Build FAISS Vector Store ──────────────────────────────────────────────────

# FAISS.from_documents embeds all chunks and builds the ANN index in one call.
# Each chunk retains its metadata (source, title, start_index) in the store.
# In production: we save with db.save_local() and load with FAISS.load_local() —
# so we don't re-embed on every restart (embedding is the expensive step).

print(f'Indexing {len(chunks)} chunks into FAISS...')
t0 = time.time()

vector_store = FAISS.from_documents(
    documents=chunks,
    embedding=embedding_model,
)

elapsed = time.time() - t0
print(f'Index built in {elapsed:.2f}s')
print(f'Total vectors indexed: {vector_store.index.ntotal}')
print(f'Vector dimensions: {vector_store.index.d}')
print()
print('Production tip: Save with vector_store.save_local("faiss_index")')
print('Load with    : FAISS.load_local("faiss_index", embedding_model)')

# ── Retrieval with Score Filtering ────────────────────────────────────────────


# adds We score-based filtering function
#
# Why it matters: if no relevant chunk exists for a query, the retriever
# should return empty (or say 'I don't know') rather than hallucinating
# an answer from low-relevance chunks.
#
# FAISS returns L2 distances. We convert to cosine similarity here.
# For normalized vectors: cosine_sim = 1 - (l2_dist^2 / 2)

def retrieve_with_scores(
    query: str,
    vector_store: FAISS,
    k: int = 3,
    score_threshold: float = 0.3,
    verbose: bool = True,
) -> list[tuple[Document, float]]:
    """Retrieve top-k chunks with cosine similarity scores, filtered by threshold."""
    # similarity_search_with_score returns (Document, score) tuples
    # For FAISS with normalized embeddings, lower score = more similar (L2 distance)

    raw_results = vector_store.similarity_search_with_score(query, k=k * 2)

    # Convert L2 distance to cosine similarity and filter
    results = []
    for doc, l2_dist in raw_results:
        # cos_sim = 1 - (l2_dist^2 / 2) for normalized vectors
        cos_sim = 1.0 - (l2_dist ** 2) / 2.0
        if cos_sim >= score_threshold:
            results.append((doc, cos_sim))

    # Return top-k after filtering, sorted by similarity (highest first)
    results = sorted(results, key=lambda x: x[1], reverse=True)[:k]

    if verbose:
        print(f'Query: "{query[:60]}"')
        print(f'Retrieved {len(results)}/{k} chunks above threshold {score_threshold}')
        for i, (doc, score) in enumerate(results):
            print(f'  [{i}] score={score:.4f} | {doc.page_content[:80]}...')
        print()

    return results


# Test retrieval on several queries
print('=== Retrieval Test ===')
results = retrieve_with_scores('How much money did the film earn?', vector_store, cfg.retrieval_k)
results2 = retrieve_with_scores('Who is the director?', vector_store, cfg.retrieval_k)
results3 = retrieve_with_scores('What is the recipe for chocolate cake?', vector_store, cfg.retrieval_k)

"""---
## Section 5 — LLM Setup: ChatGroq

### Why Groq for this notebook

Groq provides free, fast inference via API — ideal for RAG notebooks where
the focus is the retrieval pipeline, not the generation model.
The LPU (Language Processing Unit) hardware delivers much lower latency
than typical cloud GPU endpoints.

#### Temperature = 0 for RAG: why this matters

In RAG, the LLM's job is to **faithfully report what the context says**.
We do NOT want creative, surprising answers — we want accurate summaries of retrieved facts.

- `temperature=0`: Deterministic. Same context always gives the same answer. Maximally faithful.
- `temperature>0`: Introduces sampling variance. The model may paraphrase differently or introduce errors.

**Rule:** Use `temperature=0` for factual RAG. Use `temperature>0` for creative or summarization tasks.


"""

# ── LLM Initialization ───────────────────────────────────────────────────────

# ChatGroq wraps the Groq API with LangChain's BaseChatModel interface.
# This means it's swappable: replace ChatGroq with ChatOpenAI, ChatAnthropic,
# or a local HuggingFace model and the rest of the pipeline stays identical.
# That's the power of the LangChain interface abstraction.

llm = ChatGroq(
    model=cfg.llm_model,
    temperature=cfg.llm_temperature,   # 0.0 = deterministic for factual RAG
    max_tokens=cfg.llm_max_tokens,
    max_retries=2,                     # auto-retry on rate limit errors
    api_key=GROQ_API_KEY,
)

print(f'LLM initialized: {cfg.llm_model}')
print(f'Temperature: {cfg.llm_temperature} (deterministic for factual RAG)')

# Quick connectivity test — confirm API key works before building the full pipeline
t0 = time.time()
test_response = llm.invoke('Reply with exactly: API connection verified.')
elapsed = time.time() - t0
print(f'API test ({elapsed:.2f}s): {test_response.content.strip()}')

"""---
# Section 6 — The RAG Pipeline: LCEL (Modern LangChain)

## What changed from the original
 **LCEL** (LangChain Expression Language) — a pipe-based composition system:

```python
# New (LCEL):
chain = ({"context": retriever, "question": RunnablePassthrough()}) | prompt | llm | StrOutputParser()
```

## Prompt design for RAG

When using Groq (non-Phi-3 model), those tokens become literal string noise.
We use a clean, model-agnostic prompt template instead.

"""

# ── RAG Prompt Template ───────────────────────────────────────────────────────

# Prompt design principles for RAG:
# 1. Put the context BEFORE the question (anti-lost-in-middle: context near start)
# 2. Give an explicit 'no answer' instruction — prevents hallucination
# 3. Keep the instruction clear and direct
# 4. No model-specific tokens (<|user|> etc.) — use ChatPromptTemplate roles instead
# 5. Request citation where possible

RAG_PROMPT_TEMPLATE = """\
You are a precise question-answering assistant.
Use ONLY the following retrieved context to answer the question.
If the answer is not in the context, say exactly: "I cannot find this information in the provided context."
Do not add information from your training data.

Context:
{context}

Question: {question}

Answer:"""

rag_prompt = PromptTemplate(
    template=RAG_PROMPT_TEMPLATE,
    input_variables=['context', 'question'],
)

print('RAG prompt template created')
print('Key design choices:')
print('  - Context before question (anti-lost-in-middle)')
print('  - Explicit fallback instruction (prevents hallucination)')
print('  - No model-specific tokens (portable across LLMs)')

# ── Context Formatter ─────────────────────────────────────────────────────────

# Format retrieved documents into a clean context string.
# We include the source metadata so the model can acknowledge where info comes from.
# Proper formatting helps the LLM distinguish between different source chunks.

def format_docs(docs: list[Document]) -> str:
    """Format a list of Documents into a numbered context string with source attribution."""
    if not docs:
        return 'No relevant context found.'

    formatted = []
    for i, doc in enumerate(docs, 1):
        source = doc.metadata.get('source', 'unknown')
        formatted.append(
            f'[{i}] (Source: {source})\n{doc.page_content}'
        )
    return '\n\n'.join(formatted)


# Test the formatter
sample_docs = vector_store.similarity_search('film director and producer', k=2)
print('=== Formatted context example ===')
print(format_docs(sample_docs))



# ── LCEL RAG Chain (Modern Pattern) ──────────────────────────────────────────


# This is the clean, modern approach that replaces the deprecated RetrievalQA.
# LCEL chains are built with the | (pipe) operator — like Unix pipes for LLM steps.
#
# Chain steps:
#   1. RunnableParallel: runs retriever + passthrough simultaneously
#   2. rag_prompt: formats context + question into the template
#   3. llm: generates the answer
#   4. StrOutputParser: extracts the string content from the AIMessage object

retriever = vector_store.as_retriever(
    search_type='similarity',
    search_kwargs={'k': cfg.retrieval_k}
)

# Build the chain using LCEL pipe syntax
rag_chain = (
    RunnableParallel(
        context=retriever | format_docs,   # retrieve → format
        question=RunnablePassthrough(),     # pass the query straight through
    )
    | rag_prompt                           # inject into prompt template
    | llm                                  # generate
    | StrOutputParser()                    # extract string from AIMessage
)

print('RAG chain built using LCEL (modern LangChain)')
print('Chain steps: Retriever → Format → Prompt → LLM → Parse')

# Also build a chain that returns sources alongside the answer
rag_chain_with_sources = RunnableParallel(
    answer=rag_chain,
    sources=retriever,
)

print('Source-tracking chain also built')

# ── Query Runner ──────────────────────────────────────────────────────────────

# A clean wrapper that runs a query and displays formatted output.
# Reusable for all query experiments in this notebook.

def run_rag_query(
    question: str,
    chain=None,
    show_sources: bool = True,
    label: str = 'RAG',
) -> dict:
    """Run a RAG query and return answer + sources + latency."""
    if chain is None:
        chain = rag_chain_with_sources

    t0 = time.time()
    result = chain.invoke(question)
    elapsed = time.time() - t0

    answer = result.get('answer', result) if isinstance(result, dict) else result
    sources = result.get('sources', []) if isinstance(result, dict) else []

    print(f'[{label}] Q: {question}')
    print(f'  Answer ({elapsed:.2f}s):')
    print(textwrap.fill(answer.strip(), width=80, initial_indent='    ', subsequent_indent='    '))

    if show_sources and sources:
        print(f'  Sources used ({len(sources)} chunks):')
        for src in sources:
            print(f'    • {src.page_content[:70]}...')
    print()
    return {'question': question, 'answer': answer, 'sources': sources, 'latency': elapsed}


# Test the full RAG pipeline
print('=== RAG Pipeline Tests ===')
r1 = run_rag_query('How much money did IRobot earn?')
r2 = run_rag_query('Who directed IRobot and what other roles did they have?')
r3 = run_rag_query('Where was IRobot filmed?')
r4 = run_rag_query('What is Elon Musk famous for?')  # Out-of-context: should say 'cannot find'

"""---
# Section 7 — RAG vs No-RAG: Side-by-Side Comparison

## Why we done this comparison , does it matter matters

The most convincing demonstration of RAG's value is a direct comparison.
Without this, it's easy to assume the LLM already 'knows' the answer from training.

**This comparison answers:** Does the LLM hallucinate without RAG?
Can RAG correct mistakes the model would otherwise make?

**Experiment design:**
- Same LLM (ChatGroq), same temperature (0.0)
- Same questions
- Only difference: RAG chain vs direct LLM call
- Check answers against ground truth

"""

# ── Direct LLM Chain (No RAG) ─────────────────────────────────────────────────


# This is the baseline: what does the LLM answer from memory alone?
# No retrieval, no context injection — just the raw model.

direct_prompt = PromptTemplate(
    template='Answer the following question concisely from your knowledge:\n\nQuestion: {question}\n\nAnswer:',
    input_variables=['question']
)

direct_chain = direct_prompt | llm | StrOutputParser()


def run_direct_query(question: str) -> dict:
    """Run a query directly against the LLM with no RAG context."""
    t0 = time.time()
    answer = direct_chain.invoke({'question': question})
    elapsed = time.time() - t0
    print(f'[NO-RAG] Q: {question}')
    print(f'  Answer ({elapsed:.2f}s):')
    print(textwrap.fill(answer.strip(), width=80, initial_indent='    ', subsequent_indent='    '))
    print()
    return {'question': question, 'answer': answer, 'latency': elapsed}


# Side-by-side on our specific queries
comparison_questions = [
    'What was the worldwide gross of IRobot?',
    'Who was the scientific consultant for IRobot?',
    'Where was IRobot filmed?',
    'How many Academy Award nominations did IRobot receive, and which did it win?',
]

rag_results = []
direct_results = []

for q in comparison_questions:
    print('=' * 70)
    print(f'QUESTION: {q}')
    print('-' * 70)
    rag_r = run_rag_query(q, label='RAG')
    direct_r = run_direct_query(q)
    rag_results.append(rag_r)
    direct_results.append(direct_r)

# ── Hallucination Probe ───────────────────────────────────────────────────────


# Questions designed to probe hallucination — specific facts the LLM might
# confidently get wrong but the RAG system answers from the document correctly.

print('=== HALLUCINATION PROBE ===')
print('Testing a specific question that models often hallucinate on\n')

hallucination_probe = 'What awards did IRobot win, and at which ceremony?'

print('Ground truth: Won Best Visual Effects at the 87th Academy Awards.\n')

print('--- No-RAG answer ---')
direct_r = run_direct_query(hallucination_probe)

print('--- RAG answer ---')
rag_r = run_rag_query(hallucination_probe, label='RAG')

print('Analysis: RAG answer should cite the 87th Academy Awards specifically.')
print('No-RAG may guess correctly but could also introduce invented ceremony details.')



"""---
## Section 8 — Chunking Strategy Comparison

### Why chunk size is a critical hyperparameter

- **Too small chunks:** High retrieval precision but missing surrounding context
  → Answer may be correct but lacks supporting explanation
- **Too large chunks:** Rich context but lower retrieval precision
  → Retrieved chunk may contain the answer plus lots of noise
- **No overlap:** Boundary splitting loses context at chunk edges
  → A sentence split between chunks can appear in neither

**The right chunk size depends on your document type:**
- Short factual sentences → 100–200 chars
- Paragraphs with related facts → 300–500 chars
- Narrative documents → 500–1000 chars

"""

# ── Multi-Strategy Experiment Runner ─────────────────────────────────────────4


# Build multiple index variants and compare retrieval recall.
# This is how we empirically choose chunk size for a new document corpus.

def build_index(docs: list[Document], chunk_size: int, overlap: int, label: str) -> tuple:

    """Build a FAISS index with specified chunking config. Returns (store, stats)."""

    splitter = make_splitter(chunk_size, overlap)
    chunks = splitter.split_documents(docs)
    store = FAISS.from_documents(chunks, embedding_model)
    stats = inspect_chunks(chunks, label)
    return store, chunks, stats


chunking_configs = [
    {'chunk_size': 100,  'overlap': 10,  'label': 'Small  (100 chars, 10 overlap)'},
    {'chunk_size': 300,  'overlap': 50,  'label': 'Medium (300 chars, 50 overlap)'},  # our default
    {'chunk_size': 600,  'overlap': 100, 'label': 'Large  (600 chars, 100 overlap)'},
    {'chunk_size': 1000, 'overlap': 150, 'label': 'XLarge (1000 chars, 150 overlap)'},
]

# Golden test set: (query, keyword that MUST appear in retrieved chunk)
golden_queries = [
    ('How much money did IRobot earn?',   '353.13 million'),
    ('Who directed IRobot?',               'Alex Proyas'),
    ('Where was IRobot filmed?',           'Alberta'),
    ('What award did IRobot win?',         'Visual Effects'),
    ('Who was the scientific consultant?',  'Kip Thorne'),
]

print(f'=== CHUNKING STRATEGY EXPERIMENT ===')
print(f'{"Strategy":<40} {"Chunks":>7} {"Avg chars":>10} {"Recall@3":>10}')
print('-' * 72)

for config in chunking_configs:
    store, chunk_list, stats = build_index(
        [raw_doc], config['chunk_size'], config['overlap'], config['label']
    )

    # Measure Recall@3: does the correct chunk appear in the top-3 retrieved?
    correct = 0
    for query, keyword in golden_queries:
        results = store.similarity_search(query, k=3)
        retrieved_text = ' '.join(r.page_content for r in results).lower()
        if keyword.lower() in retrieved_text:
            correct += 1

    recall = correct / len(golden_queries)
    print(f'{config["label"]:<40} {stats["count"]:>7} {stats["avg_chars"]:>10.0f} {recall:>10.1%}')

print()
print('Higher recall = better retrieval for this document + query set.')
print('The "best" config is document-specific — always measure on YOUR data.')

