# -*- coding: utf-8 -*-
"""RAG_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q1e2wXfFyifzS-hSns_KDOIoDR5NvPlr

## 🔍 RAG Pipeline — Retrieval-Augmented Generation with LangChain + FAISS + Zephyr-7B
### GitHub Issues as Knowledge Base · BGE Embeddings · LCEL Chain Architecture

---

### 🧠 What is RAG (Retrieval-Augmented Generation)?

**RAG** is a technique that enhances LLMs by giving them access to *external, up-to-date knowledge* at inference time — without retraining the model.

```
User Question
     │
     ▼
 [Retriever] ──→ Searches vector DB ──→ Fetches top-k relevant chunks
     │
     ▼
 [Augmented Prompt] = System prompt + Retrieved context + User question
     │
     ▼
 [LLM] ──→ Generates answer grounded in retrieved facts
     │
     ▼
 Final Answer (cited, accurate, up-to-date)
```



---

## 🏗️ This Notebook's RAG Architecture

```
GitHub Issues (PEFT repo)
        │
        ▼
  GitHubIssuesLoader          ← LangChain document loader
        │
        ▼
RecursiveCharacterTextSplitter  ← chunk_size=512, overlap=30
        │
        ▼
  BGE Embeddings (768-dim)    ← BAAI/bge-base-en-v1.5
        │
        ▼
   FAISS Vector Store         ← Approximate Nearest Neighbor search
        │
        ▼
  Similarity Retriever (k=4)  ← Top 4 most relevant chunks
        │
        ▼
  Zephyr-7B-beta LLM          ← Mistral 7B fine-tuned on chat data
        │
        ▼
   LCEL Chain (prompt|llm|parser) ← LangChain Expression Language
        │
        ▼
  Final Answer (context-aware)
```

---
## 📦 Dependencies
- `langchain`, `langchain-community` — orchestration framework
- `faiss-cpu` — Facebook AI Similarity Search (vector DB)
- `sentence-transformers` — embedding models
- `transformers` — Hugging Face model loading
- `torch` — PyTorch backend for inference

## 📦 Section 1 — Installation

### Library roles:
- **`faiss-cpu`** — Facebook's vector similarity search library. Stores embeddings and does fast ANN (Approximate Nearest Neighbor) search. Use `faiss-gpu` if you have CUDA.
- **`langchain`** — Core orchestration: chains, prompts, output parsers
- **`langchain-community`** — Third-party integrations: FAISS, HuggingFace, GitHub loaders
- **`langchain-text-splitters`** — Document chunking strategies (often bundled with langchain now)

> 💡 **as we use Colab :** The UTF-8 locale fix is needed because some Colab instances default to ASCII,
> which causes pip to crash when downloading packages with non-ASCII metadata.
"""

# ─── Install vector store library ────────────────────────────────────────────

# faiss-cpu: pure CPU FAISS (works everywhere)
# faiss-gpu: use this on GPU Colab/Kaggle for ~10x faster index building
!pip install -q faiss-cpu

# ─── Fix for Google Colab: force UTF-8 locale ────────────────────────────────
# Without this, pip may crash on packages with unicode in their metadata
import locale
locale.getpreferredencoding = lambda: "UTF-8"

# ─── LangChain ecosystem ──────────────────────────────────────────────────────
# langchain            → core chains, prompts, LCEL operators
# langchain-community  → 3rd party integrations (HuggingFace, FAISS, GitHub, etc.)
# langchain-text-splitters → document chunking utilities
!pip install -q langchain langchain-community langchain-text-splitters

print("✅ All packages installed")

"""---
### 🔐 Section 2 — Authentication & Data Loading

## we used the github token for aoi authentication

#### Dataset: HuggingFace PEFT Issues
**PEFT** (Parameter-Efficient Fine-Tuning) is a popular HuggingFace library.  
Its GitHub issues are a great knowledge base for questions like:
- "How do I merge LoRA adapters?"
- "Why is my training loss not decreasing with QLoRA?"
- "How do I use PEFT with custom models?"

"""

from getpass import getpass

# ─── Securely prompt for GitHub Personal Access Token ────────────────────────
# getpass() hides the input so the token doesn't appear in notebook output
# NEVER hardcode tokens in notebooks — they end up in git history!
ACCESS_TOKEN = getpass("Enter your GitHub Personal Access Token: ")

print("✅ Token received (hidden for security)")

from langchain_community.document_loaders import GitHubIssuesLoader

# ─── Configure GitHub Issues Loader ──────────────────────────────────────────
# repo         → "owner/repo-name" format
# access_token → GitHub PAT for authenticated API calls (5000 req/hr)
# include_prs  → False = only Issues, not Pull Requests
# state        → "all" = open + closed issues (maximizes knowledge base size)
#                "open" = only active issues
#                "closed" = only resolved issues (tend to have answers!)

loader = GitHubIssuesLoader(
    repo="huggingface/peft",           # The PEFT library repo
    access_token=ACCESS_TOKEN,
    include_prs=False,                 # PRs have code diffs — less useful for Q&A
    state="all"                        # Load everything for maximum coverage
)

# ─── Load all issues ──────────────────────────────────────────────────────────
# This makes paginated API calls — may take 1-3 minutes for large repos

print("Loading GitHub issues... (this may take a few minutes)")
docs = loader.load()

print(f"\n✅ Loaded {len(docs)} issues from huggingface/peft")

docs[1]

# ─── Inspect document structure ──────────────────────────────────────────────

# Each doc is a LangChain Document object:
#   doc.page_content → the actual text (title + body)
#   doc.metadata     → structured info (url, state, labels, dates...)

print(f"Total documents  : {len(docs)}")
print(f"\nDocument type    : {type(docs[0])}")
print(f"\n--- Sample Document ---")
print(f"Content preview  :\n{docs[0].page_content[:400]}")
print(f"\nMetadata keys    : {list(docs[0].metadata.keys())}")

print(f"\nSample metadata  :")
for k, v in list(docs[0].metadata.items())[:6]:
    print(f"  {k:20}: {v}")



"""---
## ✂️ Section 3 — Document Chunking (Text Splitting)

### Why chunk documents?
Two critical reasons:
1. **Embedding models have token limits** — BGE base supports max 512 tokens. Longer texts get truncated.
2. **Precision of retrieval** — a 3000-word issue body as one chunk means the retriever fetches the *entire issue* even if only one paragraph is relevant. Smaller chunks = more targeted retrieval.

### RecursiveCharacterTextSplitter — how it works:
It tries to split on separators in order of preference:
```
["\n\n", "\n", " ", ""]
```


### Use cases for different splitters:
| Splitter | Best for |
|---|---|
| `RecursiveCharacterTextSplitter` | General text, GitHub issues, articles |
| `MarkdownTextSplitter` | Markdown docs, README files |
| `PythonCodeTextSplitter` | Python source code (splits on functions/classes) |
| `TokenTextSplitter` | When you need exact token control |
| `SemanticChunker` | Splits at meaning boundaries (most advanced) |

"""

from langchain_text_splitters import RecursiveCharacterTextSplitter

# ─── Configure the text splitter ─────────────────────────────────────────────

# chunk_size=512 chars → fits within BGE's 512-token limit
# chunk_overlap=30 → small buffer to avoid losing context at boundaries
#
# 💡 Improvement tip: increase overlap to 50-100 for technical docs
#    and try chunk_size=256 for higher retrieval precision

splitter = RecursiveCharacterTextSplitter(
    chunk_size=512,     # Max characters per chunk (not tokens — chars are shorter)
    chunk_overlap=30,   # Overlap between consecutive chunks for context continuity
    length_function=len,           # Use character count (default)
    add_start_index=True,          # Adds 'start_index' to metadata — useful for tracing
)

# ─── Split all documents into chunks ─────────────────────────────────────────
chunked_docs = splitter.split_documents(docs)

print(f"Original documents  : {len(docs)}")
print(f"After chunking      : {len(chunked_docs)} chunks")
print(f"Avg chunks/doc      : {len(chunked_docs)/len(docs):.1f}")
print(f"\n--- First Chunk ---")
print(f"Content:\n{chunked_docs[0].page_content}")
print(f"\nMetadata: {chunked_docs[0].metadata}")

# ─── Analyze chunk size distribution ─────────────────────────────────────────
# Understanding your chunks is essential — too small = no context, too large = imprecise retrieval

chunk_lengths = [len(c.page_content) for c in chunked_docs]

import statistics
print("Chunk length statistics (characters):")
print(f"  Min    : {min(chunk_lengths)}")
print(f"  Max    : {max(chunk_lengths)}")
print(f"  Mean   : {statistics.mean(chunk_lengths):.0f}")
print(f"  Median : {statistics.median(chunk_lengths):.0f}")
print(f"  Stdev  : {statistics.stdev(chunk_lengths):.0f}")
print()
# Show distribution buckets
buckets = {"<100 chars": 0, "100-256": 0, "256-512": 0, "512+": 0}
for l in chunk_lengths:
    if l < 100: buckets["<100 chars"] += 1
    elif l < 256: buckets["100-256"] += 1
    elif l <= 512: buckets["256-512"] += 1
    else: buckets["512+"] += 1
print("Distribution:")
for bucket, count in buckets.items():
    bar = "█" * (count // 20)
    print(f"  {bucket:12}: {count:4} chunks  {bar}")

"""---
## 🔢 Section 4 — Embeddings + FAISS Vector Store

### What are embeddings?
An embedding model converts text → a dense vector of floats (e.g. 768 numbers).  
Semantically similar texts → vectors that are close in high-dimensional space.


### BAAI/bge-base-en-v1.5 — Why this model?
BGE (BAAI General Embedding) is consistently top-ranked on the MTEB leaderboard:
- **Dimension**: 768 (smaller than bge-large's 1024 → faster, less memory)
- **Max tokens**: 512
- **Strengths**: retrieval tasks, question-answer matching, semantic search
- **Special trick**: prepend "Represent this sentence for searching relevant passages:" to queries

### What is FAISS?
Facebook AI Similarity Search — a library for:
- Storing millions of vectors efficiently
- Finding the k nearest neighbors in milliseconds
- Supports CPU and GPU
- Index types: Flat (exact), IVF (approximate, faster), HNSW (graph-based, very fast)


"""

from langchain_community.vectorstores import FAISS
from langchain_community.embeddings import HuggingFaceEmbeddings

# ─── Load BGE Embedding Model ─────────────────────────────────────────────────


# BAAI/bge-base-en-v1.5 = top-performing open embedding model (MTEB leaderboard)
# model_kwargs: pass device="cuda" for GPU acceleration
# encode_kwargs: normalize_embeddings=True → cosine similarity works correctly

# first we check if we have a gpu connection or not
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

embedding_model = HuggingFaceEmbeddings(
    model_name='BAAI/bge-base-en-v1.5',
    model_kwargs={'device': device},
    encode_kwargs={'normalize_embeddings': True}, # L2-normalize → cosine similarity
)



print(f"Embedding model loaded: BAAI/bge-base-en-v1.5")
print(f"Output dimension: 768 floats per text")
print()

# ─── Build FAISS index from chunks ────────────────────────────────────────────
# This embeds ALL chunked_docs — may take 2-10 minutes on CPU for large datasets
# Each chunk → 768-dim vector → stored in FAISS flat index
print(f"Building FAISS index for {len(chunked_docs)} chunks...")
print("(This may take a few minutes on CPU...)")

import time
t0 = time.time()
db = FAISS.from_documents(
    chunked_docs,          # List of Document objects
    embedding_model,       # Embedding model to use
)
t1 = time.time()

print(f"\n✅ FAISS index built in {t1-t0:.1f}s")
print(f"   Total vectors stored: {db.index.ntotal}")
print(f"   Index dimension     : {db.index.d}")

# ─── Save the FAISS index to disk ────────────────────────────────────────────


# This avoids re-embedding all docs every time you restart the notebook
# Load it back with: db = FAISS.load_local("faiss_peft_index", embedding_model)

db.save_local("faiss_peft_index")
print("✅ FAISS index saved to 'faiss_peft_index/' directory")
print("   Reload with: db = FAISS.load_local('faiss_peft_index', embedding_model, allow_dangerous_deserialization=True)")

# ─── Configure the Retriever ──────────────────────────────────────────────────
# The retriever is the "search engine" component of RAG
#
# search_type options:
#   "similarity"       → cosine/dot-product similarity (default, fast)
#   "mmr"              → Maximum Marginal Relevance (diverse results, slower)
#   "similarity_score_threshold" → filter by minimum similarity score
#
# search_kwargs:
#   k=4 → return top 4 most similar chunks to the query
#   fetch_k=20 (for MMR) → fetch 20, then pick 4 diverse ones

retriever = db.as_retriever(
    search_type="similarity",
    search_kwargs={'k': 4}        # Top 4 chunks retrieved per query
)

# ─── Test the retriever standalone ───────────────────────────────────────────
test_query = "How do you combine multiple adapters?"
print(f"Test retrieval for: '{test_query}'\n")

retrieved = retriever.invoke(test_query)
print(f"Retrieved {len(retrieved)} chunks:")
for i, doc in enumerate(retrieved):
    print(f"\n[Chunk {i+1}] Score available via similarity_search_with_score()")
    print(f"  URL   : {doc.metadata.get('url', 'N/A')}")
    print(f"  State : {doc.metadata.get('state', 'N/A')}")
    print(f"  Preview: {doc.page_content[:150]}...")

"""---
## 🤖 Section 5 — Loading the Zephyr-7B-beta Language Model

### What is Zephyr-7B-beta?
**Zephyr-7B-beta** is a 7-billion parameter chat model built on top of Mistral-7B:
- Base: Mistral 7B (one of the best 7B base models)
- Fine-tuned with: dDPO (Direct Preference Optimization) on synthetic chat data
- Special strength: **follows instructions very precisely** (ideal for RAG prompts)
- Chat template: `<|system|>`, `<|user|>`, `<|assistant|>` tokens


| `temperature` | 0.2 | Low = focused/deterministic; High = creative/random |
| `do_sample` | True | Sample from distribution (not pure greedy) |
| `repetition_penalty` | 1.1 | Penalizes repeating same tokens (prevents loops) |
| `max_new_tokens` | 400 | Max answer length in tokens (~300 words) |


"""

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

model_name = 'HuggingFaceH4/zephyr-7b-beta'

# ─── Check hardware ──────────────────────────────────────────────────────────

print(f"PyTorch version  : {torch.__version__}")
print(f"CUDA available   : {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU name         : {torch.cuda.get_device_name(0)}")
    vram = torch.cuda.get_device_properties(0).total_memory / 1e9
    print(f"GPU VRAM         : {vram:.1f} GB")
    print(f"Recommended dtype: torch.float16 or torch.bfloat16")
else:
    print("Running on CPU — Zephyr-7B will be very slow without GPU!")
    print("Tip: Use 4-bit quantization (see Section 10) or switch to a smaller model")

print()
print(f"Loading model: {model_name}")
print("(First run downloads ~14GB of weights — may take 10-30 mins on slow connections)")

# ─── Load tokenizer ──────────────────────────────────────────────────────────

# Tokenizer converts text ↔ token IDs
# Zephyr uses the same tokenizer as Mistral (SentencePiece BPE, 32k vocab)
tokenizer = AutoTokenizer.from_pretrained(model_name)

print(f"Tokenizer loaded")
print(f"Vocabulary size  : {tokenizer.vocab_size:,}")
print(f"Model max length : {tokenizer.model_max_length}")
print(f"Special tokens   : {tokenizer.all_special_tokens[:6]}")

# ─── Load the model ──────────────────────────────────────────────────────────

# For GPU with enough VRAM (>14GB):
#   model = AutoModelForCausalLM.from_pretrained(model_name, torch_dtype=torch.float16, device_map="auto")
#
# For 4-bit quantization (Colab Free / limited VRAM) — see Section 10 for full code:
#   from transformers import BitsAndBytesConfig
#   bnb_config = BitsAndBytesConfig(load_in_4bit=True, bnb_4bit_compute_dtype=torch.float16)
#   model = AutoModelForCausalLM.from_pretrained(model_name, quantization_config=bnb_config, device_map="auto")

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
    device_map="auto",        # Automatically places layers on GPU/CPU
    low_cpu_mem_usage=True,   # Reduces peak RAM during loading
)

param_count = sum(p.numel() for p in model.parameters())
print(f"\nModel loaded: {model_name}")
print(f"Parameters   : {param_count/1e9:.1f}B")
print(f"Device map   : {model.hf_device_map if hasattr(model, 'hf_device_map') else 'auto'}")



"""---
## 🔗 Section 6 — HuggingFace Pipeline + LangChain LCEL Chain

### HuggingFace `pipeline()` — what it does:
The `pipeline()` function wraps a model+tokenizer into a simple callable:
1. Accepts raw string input
2. Tokenizes → runs model forward pass → decodes output tokens
3. Returns generated text

### LangChain wraps it as `HuggingFacePipeline`:
This makes the HF pipeline compatible with LangChain's `|` (pipe) operator — LCEL.

### LCEL (LangChain Expression Language):
```
chain = prompt | llm | output_parser
```
Each `|` passes the output of the left side as input to the right side.  
This is just function composition with lazy evaluation and streaming support.

### Prompt Template — Zephyr Chat Format:
```
<|system|>
Answer the question based on your knowledge. Use the following context:

{context}
</s>
<|user|>
{question}
</s>
<|assistant|>
```
This matches Zephyr's training format exactly — crucial for instruction following.  
Wrong chat template → poor answer quality.

### The RAG Chain flow:
```python
{"context": retriever, "question": RunnablePassthrough()}
    | llm_chain
```
- `retriever` → automatically searches vector DB and returns text chunks
- `RunnablePassthrough()` → passes the user question through unchanged
- These feed into the prompt → LLM → output parser

"""

from langchain_community.llms import HuggingFacePipeline
from langchain_core.prompts import PromptTemplate
from transformers import pipeline
from langchain_core.output_parsers import StrOutputParser

# ─── Build HuggingFace Generation Pipeline ───────────────────────────────────
# This wraps the model + tokenizer into a callable text generator

text_generation_pipeline = pipeline(
    model=model,
    tokenizer=tokenizer,
    task="text-generation",      # We want to generate (not classify, summarize, etc.)
    temperature=0.2,             # Low temp = focused answers (good for factual Q&A)
    do_sample=True,              # Sample instead of greedy — prevents robotic text
    repetition_penalty=1.1,      # >1.0 = penalize token repetition → less loops
    return_full_text=True,       # Return prompt + completion (we strip prompt later)
    max_new_tokens=400,          # Max tokens in the answer (not counting prompt)
)

# ─── Wrap as LangChain LLM ────────────────────────────────────────────────────

# HuggingFacePipeline makes the HF pipeline compatible with LangChain's LCEL syntax

llm = HuggingFacePipeline(pipeline=text_generation_pipeline)

print("✅ LLM pipeline configured")
print(f"   Task            : text-generation")
print(f"   Temperature     : 0.2 (focused/factual)")
print(f"   Max new tokens  : 400 (~300 words)")
print(f"   Repetition pen  : 1.1")



# ─── Zephyr-Compatible Prompt Template ────────────────────────────────────────

# CRITICAL: Zephyr was trained with THIS exact chat format.
# Using wrong tags → model ignores instructions / bad output quality
#
# Format breakdown:
#   <|system|> ... </s>  → System instruction (behavior, context, rules)
#   <|user|> ... </s>    → The user's question
#   <|assistant|>        → Model starts generating here (no closing tag needed)
#
# {context} → filled by the retriever (top-k relevant chunks)
# {question} → filled by the user's actual question

prompt_template = """<|system|>
You are a helpful assistant for the HuggingFace PEFT library.
Answer ONLY based on the provided context. Do not make up information.

Context:
{context}</s>
<|user|>
{question}</s>
<|assistant|>
"""

prompt = PromptTemplate(
    input_variables=["context", "question"],
    template=prompt_template,
)

# ─── Build the LLM chain: Prompt → LLM → Parser ──────────────────────────────
# StrOutputParser: extracts the generated string from the LLM's output dict
llm_chain = prompt | llm | StrOutputParser()

print("✅ LLM chain built: PromptTemplate | HuggingFacePipeline | StrOutputParser")



from langchain_core.runnables import RunnablePassthrough

# ─── Build the full RAG Chain ─────────────────────────────────────────────────
# RAG = Retrieval + LLM chain composed together
#
# How this works step by step:
#   1. User calls: rag_chain.invoke("How do you combine multiple adapters?")
#   2. The question goes to TWO places simultaneously:
#      a. retriever → embeds the question → searches FAISS → returns 4 chunks → becomes {context}
#      b. RunnablePassthrough() → passes question unchanged → becomes {question}
#   3. Both feed into llm_chain (prompt | llm | parser)
#   4. Prompt is filled with context + question
#   5. Zephyr generates the answer
#   6. StrOutputParser extracts the answer string

retriever = db.as_retriever(
    search_type="similarity",
    search_kwargs={'k': 4}
)

rag_chain = (
    {
        "context": retriever,              # Auto-retrieves relevant chunks for the query
        "question": RunnablePassthrough()  # Passes the query through as-is
    }
    | llm_chain                            # Plugs context + question into prompt → LLM
)

print("✅ Full RAG chain assembled")
print()
print("Chain architecture:")
print("  Input (question str)")
print("    ├─ retriever → FAISS search → 4 chunks → {context}")
print("    └─ RunnablePassthrough → {question}")
print("    ↓")
print("  PromptTemplate.format(context, question)")
print("    ↓")
print("  Zephyr-7B-beta.generate()")
print("    ↓")
print("  StrOutputParser → clean answer string")

"""---
## ❓ Section 7 — Querying the RAG System

### Two modes of calling:
1. **`llm_chain.invoke()`** — LLM only, no retrieval (you supply context manually)
2. **`rag_chain.invoke()`** — Full RAG (auto-retrieves context from FAISS, then LLM)

Always prefer `rag_chain.invoke()` in production — it's the point of RAG!

### What makes a good RAG query?
- Be specific: "How do I merge LoRA adapters in PEFT?" > "adapters"
- Natural question form works well with BGE's query encoding
- The retriever handles fuzzy matching — synonyms and paraphrases are fine

"""

# ─── Define test question ─────────────────────────────────────────────────────
question = "How do you combine multiple adapters?"

print(f"Question: {question}")
print("=" * 60)

# ─── Mode 1: LLM-only (no retrieval) ─────────────────────────────────────────


# This tests what the LLM knows WITHOUT any retrieved context
# Useful for comparing RAG vs pure LLM answer quality
print("[ LLM-ONLY (no retrieval context) ]")
print("-" * 60)

llm_only_answer = llm_chain.invoke({"context": "", "question": question})

# Strip the prompt prefix from the output (return_full_text=True includes it)
# The answer starts after "<|assistant|>"

if "<|assistant|>" in llm_only_answer:
    llm_only_answer = llm_only_answer.split("<|assistant|>")[-1].strip()

print(llm_only_answer[:800])
print()



# ─── Mode 2: Full RAG Chain (retrieval + LLM) ────────────────────────────────


# This is the complete RAG pipeline:
# Question → FAISS search → Retrieved context → Prompt → Zephyr → Answer

print("[ FULL RAG ANSWER (with retrieved context) ]")
print("-" * 60)

import time
t0 = time.time()
rag_answer = rag_chain.invoke(question)
t1 = time.time()

# Extract the assistant's response
if "<|assistant|>" in rag_answer:
    rag_answer = rag_answer.split("<|assistant|>")[-1].strip()

print(rag_answer[:1200])
print()
print(f"Total RAG time: {t1-t0:.1f}s (retrieval + generation)")

# ─── See WHAT was retrieved ───────────────────────────────────────────────────

# Transparency: show which GitHub issue chunks fed into the LLM's answer

print("[ RETRIEVED CONTEXT CHUNKS ]")
print("(These are the 4 chunks FAISS found most relevant to the question)")
print("=" * 60)

retrieved_docs = retriever.invoke(question)
for i, doc in enumerate(retrieved_docs):
    print(f"\n--- Chunk {i+1} ---")
    print(f"Source URL : {doc.metadata.get('url', 'N/A')}")
    print(f"Issue state: {doc.metadata.get('state', 'N/A')}")
    print(f"Content    :\n{doc.page_content[:300]}")
    print()



"""---
## 🎯 Section 8 — Use Cases for This RAG Architecture

This same RAG pattern (Document Loader → Chunking → Embeddings → Vector DB → LLM)
can be applied to a huge range of real-world problems:

---

### 🏢 Enterprise & Business
| Use Case | Data Source | Why RAG |
|---|---|---|
| Internal IT helpdesk | Confluence/Jira pages | Too many policies for LLM to memorize |
| HR policy Q&A | Employee handbook PDFs | Private data, changes frequently |
| Legal contract review | PDF contracts | Precise clause retrieval needed |
| Financial report analysis | 10-K filings, earnings calls | Numbers must be exact |
| Customer support bot | Support tickets, FAQs | Reduce agent workload |

### 👨‍💻 Developer Tools
| Use Case | Data Source | Why RAG |
|---|---|---|
| Library documentation bot | GitHub docs, README files | Like this notebook! |
| Codebase Q&A | GitHub repos + issues | "Where is X implemented?" |
| API reference assistant | Swagger/OpenAPI specs | Structured, constantly updated |
| Stack Overflow assistant | SO dumps | Too large for context window |
| Changelog/version assistant | CHANGELOG.md files | "What changed in v2.3?" |

### 🏥 Healthcare & Research
| Use Case | Data Source | Why RAG |
|---|---|---|
| Medical literature Q&A | PubMed papers | High accuracy critical |
| Drug interaction checker | FDA database | Must cite source |
| Clinical trial finder | ClinicalTrials.gov | Structured retrieval |
| Research paper assistant | ArXiv papers | Domain-specific terminology |

### 📚 Education
| Use Case | Data Source | Why RAG |
|---|---|---|
| Textbook Q&A | PDF textbooks | Chapter-specific answers |
| Exam prep bot | Past papers + solutions | Retrieve similar questions |
| Course material chatbot | Lecture notes, slides | Personalized tutoring |

### 🔧 When NOT to use RAG:
- When data fits in context window (use long-context LLMs instead)
- When real-time data isn't needed (pure LLM may be sufficient)
- When latency is critical (RAG adds 100-500ms for retrieval)
- When relationships between docs matter more than similarity (use Knowledge Graphs)

---

"""

